/*
 * Copyright 2000-2026 Vaadin Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.vaadin.flow.component.download;

import java.io.Serializable;
import java.util.Objects;

import com.vaadin.flow.component.trigger.internal.DownloadAction;
import com.vaadin.flow.component.trigger.internal.Trigger;
import com.vaadin.flow.server.streams.DownloadHandler;
import com.vaadin.flow.shared.Registration;

/**
 * Fluent API returned from {@link Download#onClick}, used to declare what a
 * click should download. Call {@link #start(DownloadHandler)} for content
 * generated on the server, or {@link #start(String)} for a URL the application
 * already knows. The download starts in the browser at click time.
 *
 * <pre>{@code
 * Button export = new Button("Export");
 * Download.onClick(export)
 *         .start(DownloadHandler.forFile(reportFile)
 *                 .whenComplete(success -> Notification
 *                         .show(success ? "Report sent" : "Report failed")));
 * }</pre>
 *
 * The browser does not report when, or whether, the user saves the file, so
 * there is no client-side outcome callback. The transfer callbacks of the
 * {@link DownloadHandler} report whether the server finished sending it.
 */
public final class DownloadBinding implements Serializable {

    private final Trigger trigger;

    DownloadBinding(Trigger trigger) {
        this.trigger = Objects.requireNonNull(trigger);
    }

    /**
     * Starts a download of content generated by the given handler when the
     * component is clicked. The version that takes a handler is for content
     * produced on the server; the versions that take a URL are for content the
     * browser can already address.
     * <p>
     * The handler runs only when the browser requests the file, once per click.
     * The file name and response headers come from the handler, for example
     * from
     * {@link com.vaadin.flow.server.streams.DownloadEvent#setFileName(String)
     * DownloadEvent.setFileName} or the file name of a
     * {@link com.vaadin.flow.server.streams.DownloadResponse DownloadResponse}.
     * <p>
     * The handler is registered for the clicked component and follows its
     * lifecycle: it is only served while the component is attached, visible and
     * enabled. A button that disables itself on click can be disabled before
     * the browser requests the file; pass
     * {@link DownloadHandler#allowDisabled() handler.allowDisabled()} to serve
     * the file in that case.
     *
     * @param handler
     *            produces the file when the browser requests it, not
     *            {@code null}
     * @return a registration for removing the download from the component;
     *         after removal the handler is no longer served
     */
    public Registration start(DownloadHandler handler) {
        return bind(new DownloadAction(
                Objects.requireNonNull(handler, "handler must not be null")));
    }

    /**
     * Starts a download from the given URL when the component is clicked. The
     * version that takes a URL is for content the browser can already address,
     * such as a static file or a REST endpoint; the version that takes a
     * handler is for content produced on the server.
     *
     * @param url
     *            the URL to download from, not {@code null}
     * @return a registration for removing the download from the component
     */
    public Registration start(String url) {
        return bind(new DownloadAction(url));
    }

    /**
     * Like {@link #start(String)} but suggests {@code fileName} as the name of
     * the saved file. Browsers use the suggestion only for URLs of the same
     * origin; for other URLs the server has to send the name in a
     * {@code Content-Disposition} header.
     *
     * @param url
     *            the URL to download from, not {@code null}
     * @param fileName
     *            the suggested file name, not {@code null}
     * @return a registration for removing the download from the component
     */
    public Registration start(String url, String fileName) {
        return bind(new DownloadAction(url, fileName));
    }

    private Registration bind(DownloadAction action) {
        trigger.triggers(action);
        return trigger::remove;
    }
}
