/*
 * Copyright 2000-2026 Vaadin Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

// Public entry point of the flow-client jar. Resolved by flow-server's
// vite.generated.ts and imported by the web-component bootstrap generated by
// TaskGenerateWebComponentBootstrap as
// `import { init } from 'Frontend/generated/jar-resources/FlowClient.js'`.
// Keep the file path and exported `init` name stable — they're an API
// contract with flow-server / flow-build-tools.
import { Bootstrapper } from './internal/client/bootstrap/Bootstrapper.js';

export function init() {
  Bootstrapper.initModule();
}
