server.port=8888

# Use the Vite dev server (frontend hot deploy) to ease development. This is not
# strictly the framework default (which is the dev bundle), but gives the best
# developer experience for the module where most tests live.
vaadin.frontend.hotdeploy=true
