<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-parent</artifactId>
    <version>3.0.0</version>
  </parent>

  <artifactId>vaadin-cdi-parent</artifactId>
  <version>16.1-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>vaadin-cdi-parent</name>
  <description>Parent module for CDI integration for Vaadin applications.</description>
  <url>https://github.com/vaadin/cdi</url>

  <organization>
    <name>Vaadin Ltd</name>
    <url>http://vaadin.com</url>
  </organization>

  <licenses>
    <license>
      <name>Apache License 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.html</url>
    </license>
  </licenses>

  <modules>
    <module>vaadin-cdi</module>
  </modules>

  <scm>
    <connection>git:https://github.com/vaadin/cdi.git</connection>
    <developerConnection>git:https://github.com/vaadin/cdi.git</developerConnection>
    <url>https://github.com/vaadin/cdi</url>
  </scm>

  <properties>

    <encoding>UTF-8</encoding>
    <maven.compiler.release>21</maven.compiler.release>
    <maven.compiler.source>${maven.compiler.release}</maven.compiler.source>
    <maven.compiler.target>${maven.compiler.release}</maven.compiler.target>
    <maven.surefire.plugin.version>3.5.3</maven.surefire.plugin.version>
    <maven.javadoc.version>3.11.2</maven.javadoc.version>
    <driver.binary.downloader.maven.plugin.version>1.0.18</driver.binary.downloader.maven.plugin.version>

    <vaadin.flow.version>25.2-SNAPSHOT</vaadin.flow.version>
    <jakarta.ee.version>11.0.0</jakarta.ee.version>
    <slf4j.version>2.0.17</slf4j.version>
    <weld.version>6.0.3.Final</weld.version>
    <arquillian.version>1.9.5.Final</arquillian.version>
    <shrinkwrap.resolver.version>3.3.4</shrinkwrap.resolver.version>
    <shrinkwrap.descriptors.version>2.0.0</shrinkwrap.descriptors.version>
    <junit.version>4.13.2</junit.version>
    <junit5.version>5.12.2</junit5.version>
    <mockito.version>5.18.0</mockito.version>
    <weld.junit.version>5.0.1.Final</weld.junit.version>

    <spotless.plugin.version>3.5.1</spotless.plugin.version>
    <spotless.license-header>${maven.multiModuleProjectDirectory}/eclipse/apache2-license-header.txt</spotless.license-header>
    <spotless.ratchetFrom/>

  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>jakarta.platform</groupId>
        <artifactId>jakarta.jakartaee-bom</artifactId>
        <version>${jakarta.ee.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <dependency>
        <groupId>com.vaadin</groupId>
        <artifactId>flow</artifactId>
        <version>${vaadin.flow.version}</version>
      </dependency>
      <dependency>
        <groupId>com.vaadin</groupId>
        <artifactId>flow-server</artifactId>
        <version>${vaadin.flow.version}</version>
      </dependency>
      <dependency>
        <groupId>com.vaadin</groupId>
        <artifactId>flow-client</artifactId>
        <version>${vaadin.flow.version}</version>
      </dependency>
      <dependency>
        <groupId>com.vaadin</groupId>
        <artifactId>flow-html-components</artifactId>
        <version>${vaadin.flow.version}</version>
      </dependency>
      <dependency>
        <groupId>com.vaadin</groupId>
        <artifactId>flow-polymer-template</artifactId>
        <version>${vaadin.flow.version}</version>
      </dependency>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-simple</artifactId>
        <version>${slf4j.version}</version>
      </dependency>

      <dependency>
        <groupId>org.jboss.weld.se</groupId>
        <artifactId>weld-se-core</artifactId>
        <version>${weld.version}</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>${junit.version}</version>
      </dependency>
      <dependency>
        <groupId>org.mockito</groupId>
        <artifactId>mockito-core</artifactId>
        <version>${mockito.version}</version>
      </dependency>
      <dependency>
        <groupId>com.vaadin</groupId>
        <artifactId>flow-test-util</artifactId>
        <version>${vaadin.flow.version}</version>
      </dependency>
      <dependency>
        <groupId>org.lucee</groupId>
        <artifactId>jcip-annotations</artifactId>
        <version>1.0.0</version>
      </dependency>
      <dependency>
        <groupId>org.jboss.arquillian.junit</groupId>
        <artifactId>arquillian-junit-container</artifactId>
        <version>${arquillian.version}</version>
      </dependency>
      <dependency>
        <groupId>org.jboss.shrinkwrap.resolver</groupId>
        <artifactId>shrinkwrap-resolver-impl-maven</artifactId>
        <version>${shrinkwrap.resolver.version}</version>
      </dependency>
      <dependency>
        <groupId>org.jboss.shrinkwrap.descriptors</groupId>
        <artifactId>shrinkwrap-descriptors-impl-javaee</artifactId>
        <version>${shrinkwrap.descriptors.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <repositories>
    <!-- The order of definitions matters. Explicitly defining central here to make sure it has the highest priority. -->
    <repository>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>central</id>
      <url>https://repo.maven.apache.org/maven2</url>
    </repository>
    <repository>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <id>vaadin-prereleases</id>
      <url>https://maven.vaadin.com/vaadin-prereleases/</url>
    </repository>
    <!-- Repository used by many Vaadin add-ons -->
    <repository>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>Vaadin Directory</id>
      <url>https://maven.vaadin.com/vaadin-addons</url>
    </repository>
  </repositories>

  <pluginRepositories>
    <!-- The order of definitions matters. Explicitly defining central here to make sure it has the highest priority. -->
    <pluginRepository>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>central</id>
      <url>https://repo.maven.apache.org/maven2</url>
    </pluginRepository>
    <pluginRepository>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <id>vaadin-prereleases</id>
      <url>https://maven.vaadin.com/vaadin-prereleases/</url>
    </pluginRepository>
  </pluginRepositories>

  <build>
    <plugins>
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>${spotless.plugin.version}</version>
        <configuration>
          <ratchetFrom>${spotless.ratchetFrom}</ratchetFrom>
          <java>
            <eclipse>
              <file>${maven.multiModuleProjectDirectory}/eclipse/VaadinJavaConventions.xml</file>
            </eclipse>
            <endWithNewline/>
            <removeUnusedImports/>
            <importOrder>
              <file>${maven.multiModuleProjectDirectory}/eclipse/cdi.importorder</file>
            </importOrder>
            <forbidWildcardImports/>
            <licenseHeader>
              <file>${spotless.license-header}</file>
            </licenseHeader>
          </java>
          <pom>
            <sortPom>
              <expandEmptyElements>false</expandEmptyElements>
            </sortPom>
          </pom>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>default</id>
      <activation>
        <property>
          <name>!skipTests</name>
        </property>
      </activation>
      <modules>
        <module>vaadin-cdi-itest</module>
      </modules>
    </profile>
  </profiles>
</project>
