/*
 * Copyright 2000-2026 Vaadin Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.vaadin.flow.server.frontend;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.vaadin.flow.internal.FrontendUtils;

/**
 * Writes a manifest listing the frontend files generated by Flow under the
 * frontend generated folder during the current run.
 * <p>
 * This task must run after all file-generating tasks so that the manifest
 * reflects the complete set of generated files. It is only scheduled for runs
 * that actually perform a full frontend generation (development hot deploy,
 * bundle build or production build), so a standalone {@code prepare-frontend}
 * run never overwrites a manifest produced by a previous generating run.
 * <p>
 * The manifest is read by {@link TaskRemoveOldFrontendGeneratedFiles} so that a
 * later cleanup, running in a context that did not regenerate the dev-server
 * only files (such as {@link FrontendUtils#INDEX_TSX} or
 * {@link FrontendUtils#VITE_DEVMODE_TS}), does not delete them as if they were
 * stale.
 * <p>
 * For internal use only. May be renamed or removed in a future release.
 *
 * @see TaskRemoveOldFrontendGeneratedFiles
 * @see GeneratedFilesSupport
 */
public class TaskWriteGeneratedFilesList implements FallibleCommand {

    private static final Logger LOGGER = LoggerFactory
            .getLogger(TaskWriteGeneratedFilesList.class);

    private final Path frontendGeneratedFolder;
    private GeneratedFilesSupport generatedFilesSupport;

    TaskWriteGeneratedFilesList(Options options) {
        frontendGeneratedFolder = options.getFrontendGeneratedFolder().toPath()
                .toAbsolutePath().normalize();
    }

    @Override
    public void execute() throws ExecutionFailedException {
        if (generatedFilesSupport == null) {
            return;
        }
        List<String> relativePaths = generatedFilesSupport
                .getFiles(frontendGeneratedFolder).stream()
                .map(frontendGeneratedFolder::relativize).map(Path::toString)
                .sorted().collect(Collectors.toList());
        Path manifest = frontendGeneratedFolder
                .resolve(FrontendUtils.GENERATED_FILES_LIST_NAME);
        try {
            generatedFilesSupport.writeIfChanged(manifest, relativePaths);
        } catch (IOException | UncheckedIOException ex) {
            // Failing to write the manifest must not break the build; the worst
            // case is that a later cleanup deletes dev-server generated files,
            // which a subsequent generation run regenerates.
            if (LOGGER.isDebugEnabled()) {
                LOGGER.warn("Cannot write generated files manifest {}",
                        manifest, ex);
            } else {
                LOGGER.warn("Cannot write generated files manifest {}",
                        manifest);
            }
        }
    }

    @Override
    public void setGeneratedFileSupport(GeneratedFilesSupport support) {
        this.generatedFilesSupport = support;
    }

}
