/*
 * Copyright (C) 2000-2026 Vaadin Ltd
 *
 * This program is available under Vaadin Commercial License and Service Terms.
 *
 * See <https://vaadin.com/commercial-license-and-service-terms> for the full
 * license.
 */
package com.vaadin.flow.gradle

import java.io.File
import com.vaadin.flow.plugin.base.BuildFrontendUtil
import com.vaadin.flow.server.Constants
import com.vaadin.flow.server.frontend.FrontendUtils
import org.gradle.api.provider.Property
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.OutputFile

/**
 * Declaratively defines the outputs of the [VaadinPrepareFrontendTask]:
 * package.json, vite.config.ts, and other files generated by Vaadin, as well
 * as the files in the frontend directory. Being used for caching the results
 * of vaadinPrepareFrontend task to not run it again if inputs are the same.
 */
internal class PrepareFrontendOutputProperties(
    adapter: GradlePluginAdapter
) {

    private val config = adapter.config
    private val projectDir = config.projectDir
    private val generatedTsFolder =
        BuildFrontendUtil.getGeneratedFrontendDirectory(adapter)
    private val resourceOutputDirectory = config.resourceOutputDirectory

    @OutputFile
    fun getPackageJson(): File = File(projectDir, Constants.PACKAGE_JSON)

    @OutputFile
    fun getPackageLockJson(): File =
        File(projectDir, Constants.PACKAGE_LOCK_JSON)

    @OutputFile
    fun getPackageLockYaml(): File =
        File(projectDir, Constants.PACKAGE_LOCK_YAML)

    @OutputFile
    fun getViteConfig(): File =
        File(projectDir, FrontendUtils.VITE_CONFIG)

    @OutputFile
    fun getViteGeneratedConfig(): File =
        File(projectDir, FrontendUtils.VITE_GENERATED_CONFIG)

    @OutputFile
    fun getTsConfig(): File = File(projectDir, "tsconfig.json")

    @OutputFile
    fun getTsDefinition(): File = File(projectDir, "types.d.ts")

    @OutputDirectory
    fun getGeneratedTsFolder(): File = generatedTsFolder

    @OutputDirectory
    fun getResourceOutputDirectory(): Property<File> =
        resourceOutputDirectory
}
