### Changelog

All notable changes to this project will be documented in this file. Dates are displayed in UTC.

Generated by [`auto-changelog`](https://github.com/CookPete/auto-changelog).

#### [v1.14.8](https://github.com/Dexus/pem/compare/v1.14.7...v1.14.8)

- Update package.json [`fa01962`](https://github.com/Dexus/pem/commit/fa0196290854b5cd9ca67a2f9f4f28767130e5e3)

#### [v1.14.7](https://github.com/Dexus/pem/compare/v1.14.5...v1.14.7)

> 4 April 2023

- createCSR: allow special chars add note to README.md [`#232`](https://github.com/Dexus/pem/issues/232)
- createCSR: allow specialchars [`#232`](https://github.com/Dexus/pem/issues/232)
- createCertificate: now support without CSR and encrypt generated private key [`#255`](https://github.com/Dexus/pem/issues/255)
- readPkcs12: openssl v3.0.1 - fix #309 add -legacy && -tranditional option [`#309`](https://github.com/Dexus/pem/issues/309)
- Add Tests for #309, #302 [`#309`](https://github.com/Dexus/pem/issues/309) [`#302`](https://github.com/Dexus/pem/issues/302)
- Update generated files [`1fc95c8`](https://github.com/Dexus/pem/commit/1fc95c8f18599b69aac37ccc21808b2364cb45e0)
- Update mocha [`57d6162`](https://github.com/Dexus/pem/commit/57d616249d887c39d911ea05f23f5022e26399c7)
- Add Helper scripts [`cd960c4`](https://github.com/Dexus/pem/commit/cd960c46cda9de9517d49bc445162dff5528f1ad)

#### [v1.14.5](https://github.com/Dexus/pem/compare/v1.14.4...v1.14.5)

> 20 January 2022

- Verify signing chain fix [`#306`](https://github.com/Dexus/pem/pull/306)
- Fixed typo in README.md [`#300`](https://github.com/Dexus/pem/pull/300)
- Chore(deps): Bump lodash from 4.17.15 to 4.17.19 [`#299`](https://github.com/Dexus/pem/pull/299)
- Chore(deps): Bump acorn from 7.1.0 to 7.3.1 [`#298`](https://github.com/Dexus/pem/pull/298)
- Using clientKey to create http server in examples [`#293`](https://github.com/Dexus/pem/pull/293)
- Chore(deps): Bump acorn from 7.1.0 to 7.1.1 [`#289`](https://github.com/Dexus/pem/pull/289)
- Chore(deps): Bump npm from 6.13.6 to 6.14.6 [`#297`](https://github.com/Dexus/pem/pull/297)
- Update @semantic-release/github to the latest version 🚀 [`#288`](https://github.com/Dexus/pem/pull/288)
- Update @semantic-release/changelog to the latest version 🚀 [`#286`](https://github.com/Dexus/pem/pull/286)
- Update @semantic-release/npm to the latest version 🚀 [`#287`](https://github.com/Dexus/pem/pull/287)
- Update @semantic-release/git to the latest version 🚀 [`#285`](https://github.com/Dexus/pem/pull/285)
- Update semantic-release to the latest version 🚀 [`#284`](https://github.com/Dexus/pem/pull/284)
- Delete package-lock.json [`5e88b20`](https://github.com/Dexus/pem/commit/5e88b2056f5e5edb43e1ada7a0b015dbc7f59da6)
- release-v1.yml: and docs [`e0c9bee`](https://github.com/Dexus/pem/commit/e0c9bee014a8389608e470eb6517516d66ce870a)
- Support OPENSSL v3.0.0 & more [`7ec8257`](https://github.com/Dexus/pem/commit/7ec825744b9cf1a9cab37983302fa6d7da8a9b22)

#### [v1.14.4](https://github.com/Dexus/pem/compare/v1.14.3...v1.14.4)

> 25 January 2020

- fix: travis.yaml [`#283`](https://github.com/Dexus/pem/pull/283)
- fix: update readme and deps [`59c17d1`](https://github.com/Dexus/pem/commit/59c17d15674787f3a7ef9a38c9660b9ee77e770f)
- chore(release): 1.14.4 [skip ci] [`bb777c0`](https://github.com/Dexus/pem/commit/bb777c0617cda080e6635e1147a77ae5a817b384)

#### [v1.14.3](https://github.com/Dexus/pem/compare/v1.14.2...v1.14.3)

> 17 September 2019

- fix readCertificateInfo for the case when cert subject is empty [`#264`](https://github.com/Dexus/pem/pull/264)
- Greenkeeper/mocha 6.1.4 [`#252`](https://github.com/Dexus/pem/pull/252)
- Chore(deps): Bump lodash from 4.17.11 to 4.17.14 [`#253`](https://github.com/Dexus/pem/pull/253)
- Update marked to the latest version 🚀 [`#249`](https://github.com/Dexus/pem/pull/249)
- Greenkeeper/eslint plugin import 2.18.0 [`#250`](https://github.com/Dexus/pem/pull/250)
- Chore(deps): Bump js-yaml from 3.12.0 to 3.13.1 [`#248`](https://github.com/Dexus/pem/pull/248)
- Chore(deps-dev): Bump marked from 0.6.0 to 0.6.1 [`#247`](https://github.com/Dexus/pem/pull/247)
- Chore(deps): Bump lodash from 4.17.5 to 4.17.11 [`#242`](https://github.com/Dexus/pem/pull/242)
- fix(package): fix #264 & remove package-lock.josn [`#264`](https://github.com/Dexus/pem/issues/264)
- Greenkeeper/mocha 6.1.4 (#252) [`#235`](https://github.com/Dexus/pem/issues/235)
- chore(package): update eslint-plugin-import to version 2.18.0 [`#237`](https://github.com/Dexus/pem/issues/237)
- chore(release): 1.14.3 [skip ci] [`97643fa`](https://github.com/Dexus/pem/commit/97643faee7897d62eeea55fef4ba9303d6305b3f)
- chore(package): update lockfile package-lock.json [`200c2b3`](https://github.com/Dexus/pem/commit/200c2b37397e65d118c62fad594220e85eaa3c98)
- Update package-lock.json [`e4051f6`](https://github.com/Dexus/pem/commit/e4051f64cadb077e95383fbd847ef73698df3119)

#### [v1.14.2](https://github.com/Dexus/pem/compare/v1.14.1...v1.14.2)

> 16 February 2019

- Update eslint-plugin-import to the latest version 🚀 [`#231`](https://github.com/Dexus/pem/pull/231)
- chore(release): 1.14.2 [skip ci] [`e79cdaa`](https://github.com/Dexus/pem/commit/e79cdaa1be63a59e281299df56260b7a524d9e48)
- fix: Merge pull request #234 from pvangeepuram/fix-serviceKeyPassword-issue [`1649e7b`](https://github.com/Dexus/pem/commit/1649e7bb0fe45f371bd6e0509c396262b8ab58e9)
- chore(package): update lockfile package-lock.json [`1ff03dc`](https://github.com/Dexus/pem/commit/1ff03dc6afb195b5641792d96ec5c4caff72c84c)

#### [v1.14.1](https://github.com/Dexus/pem/compare/v1.14.0...v1.14.1)

> 25 January 2019

- fix(package): add altNames + csrConfigFile options to createCertificate [`#230`](https://github.com/Dexus/pem/pull/230)
- chore(release): 1.14.1 [skip ci] [`2dc1b8b`](https://github.com/Dexus/pem/commit/2dc1b8bd9af71077c453607f803a281dc3528415)

#### [v1.14.0](https://github.com/Dexus/pem/compare/v1.13.2...v1.14.0)

> 25 January 2019

- feat(package): Support SAN Certificate from CSR [`#229`](https://github.com/Dexus/pem/pull/229)
- Update eslint-plugin-import to the latest version 🚀 [`#228`](https://github.com/Dexus/pem/pull/228)
- Update marked to the latest version 🚀 [`#226`](https://github.com/Dexus/pem/pull/226)
- Greenkeeper/semantic release 15.12.5 [`#225`](https://github.com/Dexus/pem/pull/225)
- Greenkeeper/ajv 6.6.1 [`#224`](https://github.com/Dexus/pem/pull/224)
- Greenkeeper/travis deploy once 5.0.10 [`#223`](https://github.com/Dexus/pem/pull/223)
- Update eslint-plugin-node to the latest version 🚀 [`#218`](https://github.com/Dexus/pem/pull/218)
- chore(release): 1.14.0 [skip ci] [`09aa5e0`](https://github.com/Dexus/pem/commit/09aa5e0f3078200a95c44ab6c9e4351c556b81fa)
- js fix [`e5cc4bb`](https://github.com/Dexus/pem/commit/e5cc4bb955ba121e86fd821d3f4bea4a29f93c3a)

#### [v1.13.2](https://github.com/Dexus/pem/compare/v1.13.1...v1.13.2)

> 26 October 2018

- fix(package): security fix [`#217`](https://github.com/Dexus/pem/pull/217)
- chore(release): 1.13.2 [skip ci] [`9adaa05`](https://github.com/Dexus/pem/commit/9adaa05795fc1007856e721a9345d66680f4bfa6)
- Update helper.spec.js [`8e8457c`](https://github.com/Dexus/pem/commit/8e8457cd3587c0e44b213c97f815efc85c6d69c3)
- Update helper.js [`174faaf`](https://github.com/Dexus/pem/commit/174faaf191ee95afa372ec8533266f99c3f2c83c)

#### [v1.13.1](https://github.com/Dexus/pem/compare/v1.13.0...v1.13.1)

> 14 September 2018

- fix(package): remove -utf8 option [`#214`](https://github.com/Dexus/pem/issues/214)
- chore(release): 1.13.1 [skip ci] [`68ad452`](https://github.com/Dexus/pem/commit/68ad4525640dff9a4095efcf04cdb083b3aadb6f)

#### [v1.13.0](https://github.com/Dexus/pem/compare/v1.12.8...v1.13.0)

> 11 September 2018

- chore(release): 1.13.0 [skip ci] [`d5a20dd`](https://github.com/Dexus/pem/commit/d5a20ddaa4a0a6b5a79a0ec11afd4757d7176501)
- feat(package): add promisify methods pem.promisify.FUNCTIONNAME [`8a0c1bc`](https://github.com/Dexus/pem/commit/8a0c1bc5f22b213fc4386212a036c2ccb2006524)
- chore(package): update tested openssl version [`4a2754a`](https://github.com/Dexus/pem/commit/4a2754a71646798eb741e87704782618d94932ab)

#### [v1.12.8](https://github.com/Dexus/pem/compare/v1.12.7...v1.12.8)

> 11 September 2018

- chore(package): dep updates and changelog [`98a63c9`](https://github.com/Dexus/pem/commit/98a63c94b27f81984288cf5bccf5619ac8c55cf4)
- fix(pem): allow utf8 charset in fields [`2cb97aa`](https://github.com/Dexus/pem/commit/2cb97aa4d4b9de22f6a28b8cbbe95d3310b226b0)
- fix(package): dep updates and fix deprecated api [`610a403`](https://github.com/Dexus/pem/commit/610a403fef97ad6fcea0b8f6ce2d7d5160eb9f16)

#### [v1.12.7](https://github.com/Dexus/pem/compare/v1.12.6...v1.12.7)

> 11 September 2018

- fix(package): fix fetchCertificate to list all infos [`#196`](https://github.com/Dexus/pem/issues/196)
- fix(package): fix fetchCertificate to list all infos [`#196`](https://github.com/Dexus/pem/issues/196)
- chore(release): 1.12.7 [skip ci] [`7d33439`](https://github.com/Dexus/pem/commit/7d33439f2ec68360a1e0176d4888b3cd18664c0b)

#### [v1.12.6](https://github.com/Dexus/pem/compare/v1.12.5...v1.12.6)

> 10 September 2018

- Added support for -CAserial flag via options.serialFile for createCer… [`#171`](https://github.com/Dexus/pem/pull/171)
- Fix broken public key detection from PKCS#8 formatted private keys [`#212`](https://github.com/Dexus/pem/pull/212)
- Added support to specify the parameter encoding of an ecparam key [`#207`](https://github.com/Dexus/pem/pull/207)
- Update travis-deploy-once to the latest version 🚀 [`#199`](https://github.com/Dexus/pem/pull/199)
- Update eslint-plugin-import to the latest version 🚀 [`#194`](https://github.com/Dexus/pem/pull/194)
- Update package.json [`6a3f259`](https://github.com/Dexus/pem/commit/6a3f2591c344ffd692edbbd3ae0d7362ee0ba238)
- chore(release): 1.12.6 [skip ci] [`6975c5d`](https://github.com/Dexus/pem/commit/6975c5d7086dee5261514cf050efd16d55abcdec)
- Update HISTORY.md via TravisCI [`598a5ef`](https://github.com/Dexus/pem/commit/598a5ef205f55444a22cf7d3f02c4cabe26990ac)

#### [v1.12.5](https://github.com/Dexus/pem/compare/v1.12.4...v1.12.5)

> 10 April 2018

- fix: Ensure synchronous tmpfile writes, deletes [`37d7cdd`](https://github.com/Dexus/pem/commit/37d7cddecc2fc8eefd7192d85c4115ea3c45db31)
- add package-lock.json [`fa5106e`](https://github.com/Dexus/pem/commit/fa5106e6667a62331b1c4e18bc0fa6af33d4261f)
- Ensure synchronous tmpfile writes, deletes [`85a00fb`](https://github.com/Dexus/pem/commit/85a00fbd65b50db7508f094d5ffb4f20d5ef0392)

#### [v1.12.4](https://github.com/Dexus/pem/compare/v1.12.3...v1.12.4)

> 4 April 2018

- fix: pin eslint-plugin-import to 2.10.0 [`#191`](https://github.com/Dexus/pem/pull/191)
- chore(package): update semantic-release to version 15.1.5 [`#190`](https://github.com/Dexus/pem/pull/190)
- chore(package): update cross-env to version 5.1.4 [`#189`](https://github.com/Dexus/pem/pull/189)
- Update eslint-config-standard to the latest version 🚀 [`#186`](https://github.com/Dexus/pem/pull/186)
- Update eslint-plugin-node to the latest version 🚀 [`#185`](https://github.com/Dexus/pem/pull/185)
- Update mocha to the latest version 🚀 [`#183`](https://github.com/Dexus/pem/pull/183)
- Update semantic-release to the latest version 🚀 [`#182`](https://github.com/Dexus/pem/pull/182)
- Update semantic-release to the latest version 🚀 [`#178`](https://github.com/Dexus/pem/pull/178)
- Update travis-deploy-once to the latest version 🚀 [`#181`](https://github.com/Dexus/pem/pull/181)
- chore(package): update cross-env to version 5.1.2 [`#180`](https://github.com/Dexus/pem/pull/180)
- Update docco to the latest version 🚀 [`#177`](https://github.com/Dexus/pem/pull/177)
- readCertificateInfo reports email addresses in subjectAltName field [`#170`](https://github.com/Dexus/pem/pull/170)
- chore(package): update semantic-release to version 15.1.5 [`#182`](https://github.com/Dexus/pem/issues/182)
- Update HISTORY.md via TravisCI [`8e89517`](https://github.com/Dexus/pem/commit/8e895178e7701e4f0fea7a5d98a41be10a4ce457)
- Update HISTORY.md via TravisCI [`7a10bc0`](https://github.com/Dexus/pem/commit/7a10bc02fcfda92ce6bc5e971426d096c4661b0e)
- Update HISTORY.md via TravisCI [`f6a2b63`](https://github.com/Dexus/pem/commit/f6a2b6369acfd9237e9036efb9fcec30fef75a7d)

#### [v1.12.3](https://github.com/Dexus/pem/compare/v1.12.2...v1.12.3)

> 10 October 2017

- Update HISTORY.md via TravisCI [`904f74d`](https://github.com/Dexus/pem/commit/904f74dd3c53ec2c68551230e518fd16af7b2efd)
- fix(package): #117 verifySigningChain optional CA certificates [`b6aafd4`](https://github.com/Dexus/pem/commit/b6aafd4909cca8b6a1b660eb42561b0dc5d1d5fa)

#### [v1.12.2](https://github.com/Dexus/pem/compare/v1.12.1...v1.12.2)

> 8 October 2017

- fix #150: serial can now be an 20 octets string, number or hex [`#150`](https://github.com/Dexus/pem/issues/150)
- Update HISTORY.md via TravisCI [`a99b0ee`](https://github.com/Dexus/pem/commit/a99b0ee4fbd8934df815d82c17050ee82fa4ca8e)
- Update HISTORY.md via TravisCI [`b58a0b2`](https://github.com/Dexus/pem/commit/b58a0b2ea8af3620337de3bf17dfebf21a5dd353)
- chore(release-flow): create automatical a changelog before release and finish TravisCI [`b07cc19`](https://github.com/Dexus/pem/commit/b07cc191829fcf679feb08e38987d8fa1f1d56ce)

#### [v1.12.1](https://github.com/Dexus/pem/compare/v1.12.0...v1.12.1)

> 7 October 2017

- fix #159; renamed helper methods [`#159`](https://github.com/Dexus/pem/issues/159)
- converter and its tests [`ddf77eb`](https://github.com/Dexus/pem/commit/ddf77ebcdff49586da0b4c33139b46f04a919798)
- Change readme.md and history.md [`1118608`](https://github.com/Dexus/pem/commit/11186089ab01cb52b9e1ab30ccf78cab46f2c7a9)
- reviewed / extended tests and source code [`c89af35`](https://github.com/Dexus/pem/commit/c89af350abe841616955d1aaf43292d4ff020c88)

#### [v1.12.0](https://github.com/Dexus/pem/compare/v1.11.2...v1.12.0)

> 29 September 2017

- fix(package): Re-Structuring [`#147`](https://github.com/Dexus/pem/pull/147)
- fix(package): consistent usage of -password -passin and -passout [`a7c5654`](https://github.com/Dexus/pem/commit/a7c56541ede4a8979eb83d513c6521efcbb1dd96)
- feat: add createEcparam to create EC private keys [`6c991b5`](https://github.com/Dexus/pem/commit/6c991b58d220f7c11d7e0274f2faa3c788db24eb)
- standardjs setup / README.md review [`519c2cf`](https://github.com/Dexus/pem/commit/519c2cfa49fbf14616e3cc4d758d7fad8b72f69f)

#### [v1.11.2](https://github.com/Dexus/pem/compare/v1.11.1...v1.11.2)

> 21 September 2017

- fix(package): max 20 octets for serial [`#141`](https://github.com/Dexus/pem/pull/141)
- fix(package): max 20 octets for serial (#141) [`#84`](https://github.com/Dexus/pem/issues/84)
- Update .travis.yml [`bed4f44`](https://github.com/Dexus/pem/commit/bed4f44201b5c65fb20607d4f74faf44d5704831)

#### [v1.11.1](https://github.com/Dexus/pem/compare/v1.11.0...v1.11.1)

> 20 September 2017

- fix(package): fix check pkcs12 openssl1.1.0 not printed "MAC verified OK" [`#140`](https://github.com/Dexus/pem/pull/140)
- fix(package): parse serial and getDhparamInfo [`#139`](https://github.com/Dexus/pem/pull/139)
- Update semantic-release to the latest version 🚀 [`#134`](https://github.com/Dexus/pem/pull/134)
- chore(package): update semantic-release to version 8.0.0 [`efe156e`](https://github.com/Dexus/pem/commit/efe156ec02529ab9dde77dd022d4f7f5784d29bf)

#### [v1.11.0](https://github.com/Dexus/pem/compare/v1.9.8...v1.11.0)

> 13 September 2017

- Support reading array of organizations in a CSR [`#125`](https://github.com/Dexus/pem/pull/125)
- Fix #132 new version 1.10.1 [`#132`](https://github.com/Dexus/pem/issues/132)
- feat: use standard (https://standardjs.com) for coding style guide [`c48736b`](https://github.com/Dexus/pem/commit/c48736bfe4eebbcbccd7d29fe6718fe242046d40)
- Change Nodejs versions to support v8 [`26d0849`](https://github.com/Dexus/pem/commit/26d0849e02f34861c7423cc399f11362c8a53d27)
- Fix Build [`4c39ca7`](https://github.com/Dexus/pem/commit/4c39ca70bd262cfce65e236c451ff0f2f424a47e)

#### [v1.9.8](https://github.com/Dexus/pem/compare/v1.9.6...v1.9.8)

> 3 September 2017

- Feature Request: add checking support and md5 hashing for getModulus [`#127`](https://github.com/Dexus/pem/pull/127)
- Allow array values for CSRs [`#124`](https://github.com/Dexus/pem/pull/124)
-  fix a problem with parsing "Public Key size" in different OS [`#122`](https://github.com/Dexus/pem/pull/122)
- chore(package): update semantic-release to version 7.0.2 [`#128`](https://github.com/Dexus/pem/issues/128)
- Version 1.9.8 [`2eae57c`](https://github.com/Dexus/pem/commit/2eae57cafa58ba5917676ab4c84b44e0adeb8eb1)
- bump version [`44b1f17`](https://github.com/Dexus/pem/commit/44b1f1718ec9720c9f0d5051285982edb5b27624)

#### [v1.9.6](https://github.com/Dexus/pem/compare/v1.9.4...v1.9.6)

> 27 April 2017

- Documentation [`#121`](https://github.com/Dexus/pem/pull/121)
- add 3 fields to certificate parsing [`#120`](https://github.com/Dexus/pem/pull/120)
- Update README [`#119`](https://github.com/Dexus/pem/pull/119)
- Revert "Regex support for new format with spaces" [`#113`](https://github.com/Dexus/pem/pull/113)
- Regex support for new format with spaces [`#111`](https://github.com/Dexus/pem/pull/111)
- Greenkeeper/initial [`#110`](https://github.com/Dexus/pem/pull/110)
- Propagate original options from createCSR to createCertificate [`#106`](https://github.com/Dexus/pem/pull/106)
- Handle slproweb.com openssl Binaries outputting ' = ' rather than '=' to separate subject fields [`#98`](https://github.com/Dexus/pem/pull/98)
- Regex support for new format with spaces: " C = GB, ST = England, O = Organisation, OU = Provisioning, CN = CommonName, emailAddress = email@address.com" [`ca0b353`](https://github.com/Dexus/pem/commit/ca0b353f3bd18abcbcaa395138ff52c690ab8182)
- docs(readme): add Greenkeeper badge [`cfbf14e`](https://github.com/Dexus/pem/commit/cfbf14e9bda09d28b796d8f692c5ac6b7814631b)
- chore(package): update dependencies [`805fa3a`](https://github.com/Dexus/pem/commit/805fa3a4bb101511282677a9a58fc502355d39e0)

#### [v1.9.4](https://github.com/Dexus/pem/compare/v1.9.1...v1.9.4)

> 1 December 2016

- Fix error handling and deprecation warnings [`#93`](https://github.com/Dexus/pem/pull/93)
- Add support for DC Certificates fix #83 [`#83`](https://github.com/Dexus/pem/issues/83)
- release v1.9.3 [`bf6b4cd`](https://github.com/Dexus/pem/commit/bf6b4cd9889fc60fd889ccc1d2a0421ce4659e43)

#### [v1.9.1](https://github.com/Dexus/pem/compare/v1.9.0...v1.9.1)

> 28 November 2016

- fix: travis [`414b433`](https://github.com/Dexus/pem/commit/414b433bb2258638d3d1b6f6249f69dbeec014c2)
- improvement: travis versions [`42b095f`](https://github.com/Dexus/pem/commit/42b095fef55deec220c76ece72cf37c41f188289)
- improvement: use in forEach unlinkSync instand of unlink (async) [`2f7a6b6`](https://github.com/Dexus/pem/commit/2f7a6b63bea9d5c7f02db003629924cc4833f580)

#### [v1.9.0](https://github.com/Dexus/pem/compare/v1.8.3...v1.9.0)

> 28 November 2016

- Fix error handling and deprecation warnings [`#93`](https://github.com/Dexus/pem/pull/93)
- Added noop callback (Node 7.0 deprecation warning) [`#91`](https://github.com/Dexus/pem/pull/91)
- Fixing CSR subject generation [`#90`](https://github.com/Dexus/pem/pull/90)
- adding options for -CAcreateserial [`#87`](https://github.com/Dexus/pem/pull/87)
- combine getModulus and getModulusFromProtected [`#82`](https://github.com/Dexus/pem/pull/82)
- remove default empty string and replace forEach with map [`#81`](https://github.com/Dexus/pem/pull/81)
- refactor spawnWrapper [`#80`](https://github.com/Dexus/pem/pull/80)
- Only generate altNames config if it is a non-empty array [`#78`](https://github.com/Dexus/pem/pull/78)
- Only generate altNames config if it is a non-empty array (#78) [`#77`](https://github.com/andris9/pem/issues/77)
- semver [`3018e51`](https://github.com/Dexus/pem/commit/3018e5128e49fd4e6489c0915335483c993cb9d7)

#### [v1.8.3](https://github.com/Dexus/pem/compare/1.8.1...v1.8.3)

> 2 May 2016

- Support csr config [`#75`](https://github.com/Dexus/pem/pull/75)
- Allow commas in CSR fields [`#74`](https://github.com/Dexus/pem/pull/74)
- Update package.json versions [`#70`](https://github.com/Dexus/pem/pull/70)
- Refactor temp dir logic [`#63`](https://github.com/Dexus/pem/pull/63)
- Add CA certs to pkcs12 file and read pkcs12 files [`#62`](https://github.com/Dexus/pem/pull/62)
- Allow commas in CSR fields (#74) [`#73`](https://github.com/Dexus/pem/issues/73)
- prepare new release [`e7f9fba`](https://github.com/Dexus/pem/commit/e7f9fbae5a4bea25a9c2bc858ec53fd070bf37d4)
- refactor temp dir logic, uses a ponyfill [`77e2ada`](https://github.com/Dexus/pem/commit/77e2adaaff7b24f2bce7e4c8d1469f78ab4f5550)
- npm i which -S [`912e32e`](https://github.com/Dexus/pem/commit/912e32e9d0dc956366acb25c20eff1c292cd166a)

#### [1.8.1](https://github.com/Dexus/pem/compare/1.8.0...1.8.1)

> 20 September 2015

- No match fix at preg_match_all [`#61`](https://github.com/Dexus/pem/pull/61)
- Bump version to 1.8.1 [`a7e661d`](https://github.com/Dexus/pem/commit/a7e661ddb37a570af44e221306a1c406bd4d6703)
- Update .travis.yml [`89a4518`](https://github.com/Dexus/pem/commit/89a4518e368bb1231044557518a025fec92da737)
- Update travis.yml to run on container infrastructure. [`aaf979e`](https://github.com/Dexus/pem/commit/aaf979e3f0b91d6426ac2610dae2793a4613c908)

#### [1.8.0](https://github.com/Dexus/pem/compare/v1.7.1...1.8.0)

> 26 August 2015

- Adds method to verify a certificate's signing chain [`#60`](https://github.com/Dexus/pem/pull/60)
- Added functionality to export key and certificate to PKCS12 keystore [`#59`](https://github.com/Dexus/pem/pull/59)
- Added functionality to get modulus from a  password protected key [`#53`](https://github.com/Dexus/pem/pull/53)
- Include Issuer Data with Fetch Cert Data Function [`#50`](https://github.com/Dexus/pem/pull/50)
- fix / add #57, #56, #55, #54, #52 [`30f4a0a`](https://github.com/Dexus/pem/commit/30f4a0a9f6942295af4c62d9e4dd94e81ef4f9be)
- added getModulusFromProtected method and tests [`0a5cb13`](https://github.com/Dexus/pem/commit/0a5cb1316bd312c76842539f88d92e1aca5a6154)
- added signed cert methods [`2f8c1d1`](https://github.com/Dexus/pem/commit/2f8c1d1a981586c3b5053ab92afa1176108173bc)

#### [v1.7.1](https://github.com/Dexus/pem/compare/v1.7.0...v1.7.1)

> 27 February 2015

- Creating a CSR for an encrypted key [`#49`](https://github.com/Dexus/pem/pull/49)
- bump to 1.7.0 [`#2`](https://github.com/Dexus/pem/pull/2)
- * Change variable name [`e2edba6`](https://github.com/Dexus/pem/commit/e2edba6d1bb98b5204a0d4cd561d759f8fd41c9a)
- Using files for passing key passwords [`ed3a7a2`](https://github.com/Dexus/pem/commit/ed3a7a2f5c86bacce8b1967ec8e6386ba4852f8a)
- Unlinked temporary password file for CSR generation [`6e13a14`](https://github.com/Dexus/pem/commit/6e13a1421f84d7358737a8aec3016b569dc1f903)

#### [v1.7.0](https://github.com/Dexus/pem/compare/v1.6.0...v1.7.0)

> 25 February 2015

- Private key encryption [`#48`](https://github.com/Dexus/pem/pull/48)
- Merge latest PEM version [`#1`](https://github.com/Dexus/pem/pull/1)
- Add optional params to createPrivateKey [`942e937`](https://github.com/Dexus/pem/commit/942e9374e10920c40e45df8eec3994f405a6a4ad)
- Bumped version to v1.7.0 [`dbae78a`](https://github.com/Dexus/pem/commit/dbae78a72b1d04c68b3dc253caf14b68bc5083a8)

#### [v1.6.0](https://github.com/Dexus/pem/compare/v1.5.0...v1.6.0)

> 24 February 2015

- Add function to create dhparam keys [`#47`](https://github.com/Dexus/pem/pull/47)
- Updated tests [`5034d3e`](https://github.com/Dexus/pem/commit/5034d3ea1853604be4f666818500072fe43e63b0)
- Add hash option to getFingerprint function [`d8556de`](https://github.com/Dexus/pem/commit/d8556de06e7e4ffda13eb5951f9042bc5e770890)
- Bumped version to v1.6.0 [`11219a9`](https://github.com/Dexus/pem/commit/11219a95cb79279f3f0bee33b56700e196041984)

#### [v1.5.0](https://github.com/Dexus/pem/compare/v1.4.6...v1.5.0)

> 19 January 2015

- add node which to check if the user has openssl on their system [`b44c619`](https://github.com/Dexus/pem/commit/b44c619d515de7e3bbd9fdbba994827dadcb4b0f)
- Added a testcase for testOpenSSLPath [`2cd2135`](https://github.com/Dexus/pem/commit/2cd2135f6b5f9c8414147ebe991ef1345fd5e6cf)
- Changed e-mail address in travis conf [`a308e55`](https://github.com/Dexus/pem/commit/a308e5532580f1628b0263efc6c211b86ee816ec)

#### [v1.4.6](https://github.com/Dexus/pem/compare/v1.4.5...v1.4.6)

> 18 January 2015

- Just added indentations [`#39`](https://github.com/Dexus/pem/pull/39)
- Fix to catch errors on spawn [`#38`](https://github.com/Dexus/pem/pull/38)
- Update pem.js [`#36`](https://github.com/Dexus/pem/pull/36)
- Applied unified code style [`e756da6`](https://github.com/Dexus/pem/commit/e756da6cb131c5600e1798be4cf93d8cbd67e6ae)
- added the code necessary to catch the error event from the spawn and send it to the callback [`b2941ab`](https://github.com/Dexus/pem/commit/b2941ab0aa19058ae4d708de01e7389d1c4ee6f8)
- Bumped version to v1.4.6 [`fe10527`](https://github.com/Dexus/pem/commit/fe105279662b23074793225a09f7bdb0fcb7ed61)

#### [v1.4.5](https://github.com/Dexus/pem/compare/v1.4.4...v1.4.5)

> 5 January 2015

- Bugfix pathOpenSSL typo; Add environmental option for openssl binary [`#33`](https://github.com/Dexus/pem/pull/33)
- Add missing serviceCertificate & serial option to the doc [`#32`](https://github.com/Dexus/pem/pull/32)
- bumped version to 1.4.5 [`524142d`](https://github.com/Dexus/pem/commit/524142d052535a022dce9f6215ce95b663e528f4)

#### [v1.4.4](https://github.com/Dexus/pem/compare/v1.4.3...v1.4.4)

> 13 December 2014

- Update README.md [`#28`](https://github.com/Dexus/pem/pull/28)
- Add hash option for createCertificate(), default to sha256 [`#29`](https://github.com/Dexus/pem/pull/29)
- Bumped version to v1.4.4 [`1acbb32`](https://github.com/Dexus/pem/commit/1acbb3265ef078e8f3f2419814ed8ed76b5850fd)

#### [v1.4.3](https://github.com/Dexus/pem/compare/v1.4.2...v1.4.3)

> 9 December 2014

- Update README.md to correct copy/paste error [`#26`](https://github.com/Dexus/pem/pull/26)
- Add OpenSSL path config() [`#25`](https://github.com/Dexus/pem/pull/25)
- bumped version to v1.4.3 [`0ed6ecd`](https://github.com/Dexus/pem/commit/0ed6ecd1f79d991b2d018060c71865a8cedfcddc)

#### [v1.4.2](https://github.com/Dexus/pem/compare/v1.4.1...v1.4.2)

> 28 November 2014

- getModulus() will now accept Buffers [`#24`](https://github.com/Dexus/pem/pull/24)
- Bumped version to v1.4.2 [`d21f40d`](https://github.com/Dexus/pem/commit/d21f40d163b261f4e904be093b544992bdca042d)

#### [v1.4.1](https://github.com/Dexus/pem/compare/v1.4.0...v1.4.1)

> 10 May 2014

- fix wildcard certificate creation [`#19`](https://github.com/Dexus/pem/pull/19)
- fix wildcard certificate [`5a5a828`](https://github.com/Dexus/pem/commit/5a5a828d365e5d346a46925b9b77845344186d90)
- bumped version to v1.4.1 [`97c0ecc`](https://github.com/Dexus/pem/commit/97c0ecca0d3b0a13b5c4c90a7e1ba6dc788e16ce)

#### [v1.4.0](https://github.com/Dexus/pem/compare/v1.3.0...v1.4.0)

> 27 March 2014

- Change to BEGIN(\sNEW)? CERTIFICATE REQUEST [`#15`](https://github.com/Dexus/pem/pull/15)
- bumped version to 1.4.0 [`aba2be9`](https://github.com/Dexus/pem/commit/aba2be9cfdc080f637a555fb69f3beef1f9cd686)
- fixed errors [`1aee604`](https://github.com/Dexus/pem/commit/1aee604fcad0a7e122a81b4facaf2208b90eaafa)
- Change default settings for future requirements + EV Fix [`0e017e0`](https://github.com/Dexus/pem/commit/0e017e011e0b6542b776aca203add02ee7192246)

### [v1.3.0](https://github.com/Dexus/pem/compare/v0.2.2...v1.3.0)

> 18 March 2014

- Change SAN CSR process. [`#13`](https://github.com/Dexus/pem/pull/13)
- add SAN integration for readCertificateInfo [`#12`](https://github.com/Dexus/pem/pull/12)
- Easier to set temp dir, and all temp files are unlinked after use [`#11`](https://github.com/Dexus/pem/pull/11)
- altNames option to set subjectAltName [`#10`](https://github.com/Dexus/pem/pull/10)
- jshinted code [`7f8f307`](https://github.com/Dexus/pem/commit/7f8f30794e4e7943154fe30a58576bbfcfc1849d)
- add altNames option [`dc33104`](https://github.com/Dexus/pem/commit/dc331048a9f2500561df380a732123863303c7a2)
- SAN (DNS, IP) [`5060816`](https://github.com/Dexus/pem/commit/5060816bf9eafa67a7c1c9c0880b327158325d13)

#### [v0.2.2](https://github.com/Dexus/pem/compare/v0.2.1...v0.2.2)

> 17 June 2013

- Add certificate validity information to readCertificateInfo callback [`#9`](https://github.com/Dexus/pem/pull/9)
- fix unit test [`8aff869`](https://github.com/Dexus/pem/commit/8aff869b3e7036c16c9c6da32d0b3ef2b8df1cc4)
- add validity information in readCertificateInfo [`cfdae1c`](https://github.com/Dexus/pem/commit/cfdae1c5df1b8cee1318460c30ef7c1ce2ef39c1)
- validity as timestamps [`338a94f`](https://github.com/Dexus/pem/commit/338a94fe67b073efe3b25907d469da7eaa618486)

#### [v0.2.1](https://github.com/Dexus/pem/compare/v0.2.0...v0.2.1)

> 9 June 2013

- update README.md, and improve unit test for getModulus function [`#8`](https://github.com/Dexus/pem/pull/8)
- add getModulus function [`#7`](https://github.com/Dexus/pem/pull/7)
- use wrapper for openssl [`44d5f58`](https://github.com/Dexus/pem/commit/44d5f580ae2181e584e6f75372687279ee7c49a4)
- add getModulus function, useful to check that a Private Key Matches a Certificate [`f1d13d6`](https://github.com/Dexus/pem/commit/f1d13d68799b28b03047f73a816ae335766c1602)
- merged README from konsumer branch [`ab2e5f5`](https://github.com/Dexus/pem/commit/ab2e5f5fc5b3cc8449233169e3d94fcc60eb0ad6)

#### [v0.2.0](https://github.com/Dexus/pem/compare/v0.1.0...v0.2.0)

> 17 April 2013

- Add getFingerprint, fix intermittent failure [`#1`](https://github.com/Dexus/pem/pull/1)
- Add a getFingerprint method, docs, and unit test. [`0a720c7`](https://github.com/Dexus/pem/commit/0a720c763527c323bf0d071e145e09f22859025d)
- update [`52fdc25`](https://github.com/Dexus/pem/commit/52fdc2511fc2adce897aaa86f1bf0e04ee7c723e)
- travis file [`6595e7d`](https://github.com/Dexus/pem/commit/6595e7d04b151caecab363590e274ac6d55e5208)

#### v0.1.0

> 25 June 2012

- added tests [`85d2d09`](https://github.com/Dexus/pem/commit/85d2d0992d9a2ea055f5cea9fa669f467f7f5f28)
- version 0.1.0 [`44c08bc`](https://github.com/Dexus/pem/commit/44c08bc5c2cf142f42d06fa72bbf16df38190d33)
- initial [`ca5ff33`](https://github.com/Dexus/pem/commit/ca5ff33275f9d3460e1e2f8957a1320d8396f672)
