/*
 * Copyright 2000-2026 Vaadin Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.vaadin.client;

import jsinterop.annotations.JsIgnore;
import jsinterop.annotations.JsMethod;
import jsinterop.annotations.JsType;

import com.google.gwt.core.client.GWT;
import com.google.gwt.core.client.JavaScriptObject;
import com.google.gwt.core.client.Scheduler;

import com.vaadin.client.communication.LoadingIndicatorConfigurator;
import com.vaadin.client.communication.PollConfigurator;
import com.vaadin.client.communication.ReconnectConfiguration;
import com.vaadin.client.flow.StateNode;
import com.vaadin.client.flow.binding.Binder;
import com.vaadin.client.flow.collection.JsArray;
import com.vaadin.client.flow.dom.DomApi;
import com.vaadin.client.flow.util.NativeFunction;
import com.vaadin.flow.internal.nodefeature.NodeFeatures;
import com.vaadin.flow.internal.nodefeature.NodeProperties;

import elemental.client.Browser;
import elemental.dom.Element;
import elemental.dom.Node;
import elemental.json.JsonObject;

/**
 * Main class for an application / UI.
 * <p>
 * Initializes the registry and starts the application.
 * <p>
 * The methods that make up the client-side API published on
 * {@code window.Vaadin.Flow.clients[appId]} are exported to JavaScript via
 * {@link JsType}, so the publication of that object can be migrated to
 * TypeScript. See {@code MIGRATION_STRATEGY.md}.
 *
 * @since 1.0
 */
@JsType(namespace = "Vaadin.Flow.internal", name = "ApplicationConnection")
public class ApplicationConnection {

    private final Registry registry;

    /**
     * Creates an application connection using the given configuration.
     *
     * @param applicationConfiguration
     *            the configuration object for the application
     */
    @JsIgnore
    public ApplicationConnection(
            ApplicationConfiguration applicationConfiguration) {

        registry = new DefaultRegistry(this, applicationConfiguration);
        GWT.setUncaughtExceptionHandler(
                registry.getSystemErrorHandler()::handleError);

        StateNode rootNode = registry.getStateTree().getRootNode();

        // Bind UI configuration objects
        PollConfigurator.observe(rootNode, registry.getPoller());
        ReconnectConfiguration.bind(registry.getConnectionStateHandler());
        LoadingIndicatorConfigurator.observe(rootNode);

        Element body = Browser.getDocument().getBody();

        rootNode.setDomNode(body);
        Binder.bind(rootNode, body);

        Console.debug("Starting application "
                + applicationConfiguration.getApplicationId());

        String appRootPanelName = applicationConfiguration.getApplicationId();
        // remove the end (window name) of autogenerated rootpanel id
        appRootPanelName = appRootPanelName.replaceFirst("-\\d+$", "");

        boolean productionMode = applicationConfiguration.isProductionMode();
        boolean requestTiming = applicationConfiguration.isRequestTiming();
        publishJavascriptMethods(appRootPanelName, productionMode,
                requestTiming,
                applicationConfiguration.getExportedWebComponents());
        if (!productionMode) {
            String servletVersion = applicationConfiguration
                    .getServletVersion();
            publishDevelopmentModeJavascriptMethods(appRootPanelName,
                    servletVersion);
            Console.debug(
                    "Vaadin application servlet version: " + servletVersion);
        }
    }

    /**
     * Starts this application.
     * <p>
     * Called by the bootstrapper, which ensures applications are started in
     * order.
     *
     * @param initialUidl
     *            the initial UIDL or null if the server did not provide any
     */
    public void start(ValueMap initialUidl) {
        if (initialUidl == null) {
            // initial UIDL not in DOM, request from server
            registry.getMessageSender().resynchronize();
        } else {
            // initial UIDL provided in DOM, continue as if returned by request

            // Hack to avoid logging an error in endRequest()
            registry.getRequestResponseTracker().startRequest();
            registry.getMessageHandler().handleMessage(initialUidl);
        }

        Browser.getWindow().addEventListener("pagehide", e -> {
            registry.getMessageSender().sendUnloadBeacon();
        });

        Browser.getWindow().addEventListener("pageshow", e -> {
            // Currently only Safari gets here, sometimes when going back/foward
            // with browser buttons
            // Chrome discards our state as beforeunload is used
            // As state is most likely cleared on the server already (especially
            // now with Beacon API request, it is probably
            // better resyncronize the state (would happen on first server
            // visit)
            Browser.getWindow().getLocation().reload();
        });
    }

    /**
     * Checks if there is some work to be done on the client side.
     *
     * @return true if the client has some work to be done, false otherwise
     */
    public boolean isActive() {
        return !registry.getMessageHandler().isInitialUidlHandled()
                || registry.getRequestResponseTracker().hasActiveRequest()
                || isExecutingDeferredCommands();
    }

    /**
     * Triggers a server poll.
     */
    public void poll() {
        registry.getPoller().poll();
    }

    /**
     * Resolves a Vaadin URI (e.g. one using the {@code context://} or
     * {@code base://} protocol) to an absolute URL.
     *
     * @param uri
     *            the URI to resolve
     * @return the resolved URI
     */
    public String resolveUri(String uri) {
        return registry.getURIResolver().resolveVaadinUri(uri);
    }

    /**
     * Sends an event message to the server.
     *
     * @param nodeId
     *            the id of the node firing the event
     * @param eventType
     *            the type of the event
     * @param eventData
     *            the event data, or {@code null} if there is no data
     */
    public void sendEventMessage(int nodeId, String eventType,
            JsonObject eventData) {
        registry.getServerConnector().sendEventMessage(nodeId, eventType,
                eventData);
    }

    /**
     * Gets the id of the UI this application connection is connected to.
     *
     * @return the UI id
     */
    public int getUIId() {
        return registry.getApplicationConfiguration().getUIId();
    }

    /**
     * Connects the web component described by the given event data with the
     * server.
     *
     * @param eventData
     *            the event data describing the web component to connect
     */
    public void connectWebComponent(JsonObject eventData) {
        int nodeId = registry.getStateTree().getRootNode().getId();
        registry.getServerConnector().sendEventMessage(nodeId,
                "connect-web-component", eventData);
    }

    /**
     * Returns a JSON description of the root node's state tree, for debugging.
     *
     * @return the debug JSON of the root node
     */
    public JsonObject debug() {
        return registry.getStateTree().getRootNode().getDebugJson();
    }

    /**
     * Methods published to JavaScript.
     *
     * @param applicationId
     *            the application id provided by the server
     * @param productionMode
     *            <code>true</code> if running in production mode,
     *            <code>false</code> otherwise
     * @param requestTiming
     *            <code>true</code> if request timing info should be made
     *            available, <code>false</code> otherwise
     * @param exportedWebComponents
     *            a list of web component tags exported by this UI
     */
    private native void publishJavascriptMethods(String applicationId,
            boolean productionMode, boolean requestTiming,
            String[] exportedWebComponents)
    /*-{
        var ap = this;
        var client = {};
        client.isActive = $entry(function() {
            return ap.@ApplicationConnection::isActive()();
        });
        client.getByNodeId = $entry(function(nodeId) {
            return ap.@ApplicationConnection::getDomElementByNodeId(*)(nodeId);
        });
        client.getNodeId = $entry(function(element) {
            return ap.@ApplicationConnection::getNodeId(*)(element);
        });
        client.getUIId = $entry(function() {
            return ap.@com.vaadin.client.ApplicationConnection::getUIId()();
        });
        client.addDomBindingListener = $entry(function(nodeId, callback) {
            ap.@ApplicationConnection::addDomSetListener(*)(nodeId, callback);
        });
        client.productionMode = productionMode;
        client.poll = $entry(function() {
            ap.@com.vaadin.client.ApplicationConnection::poll()();
        });
        client.connectWebComponent = $entry(function(eventData) {
            ap.@com.vaadin.client.ApplicationConnection::connectWebComponent(*)(eventData);
        });
        if (requestTiming) {
           client.getProfilingData = $entry(function() {
            var smh = ap.@com.vaadin.client.ApplicationConnection::registry.@com.vaadin.client.Registry::getMessageHandler()();
            var pd = [
                smh.@com.vaadin.client.communication.MessageHandler::lastProcessingTime,
                    smh.@com.vaadin.client.communication.MessageHandler::totalProcessingTime
                ];
            if (null != smh.@com.vaadin.client.communication.MessageHandler::serverTimingInfo) {
                pd = pd.concat(smh.@com.vaadin.client.communication.MessageHandler::serverTimingInfo);
            } else {
                pd = pd.concat(-1, -1);
            }
            pd[pd.length] = smh.@com.vaadin.client.communication.MessageHandler::bootstrapTime;
            return pd;
        });
        }
        client.resolveUri = $entry(function(uriToResolve) {
            return ap.@com.vaadin.client.ApplicationConnection::resolveUri(*)(uriToResolve);
        });
        client.sendEventMessage = $entry(function(nodeId, eventType, eventData) {
            ap.@com.vaadin.client.ApplicationConnection::sendEventMessage(*)(nodeId, eventType, eventData);
        });
        client.initializing = false;
        client.exportedWebComponents = exportedWebComponents;
        $wnd.Vaadin.Flow.clients[applicationId] = client;
    }-*/;

    /**
     * Gets the DOM element bound to the state node with the given id.
     *
     * @param id
     *            the node id
     * @return the bound DOM element, or {@code null} if none
     */
    @JsMethod(name = "getByNodeId")
    public Node getDomElementByNodeId(int id) {
        StateNode node = registry.getStateTree().getNode(id);
        return node == null ? null : node.getDomNode();

    }

    private String getJavaClass(int id) {
        StateNode node = registry.getStateTree().getNode(id);
        return node == null ? null
                : node.getMap(NodeFeatures.ELEMENT_DATA)
                        .getProperty(NodeProperties.JAVA_CLASS)
                        .getValueOrDefault(null);
    }

    private boolean isHiddenByServer(int id) {
        StateNode node = registry.getStateTree().getNode(id);
        boolean visible = node == null ? true
                : node.getMap(NodeFeatures.ELEMENT_DATA)
                        .getProperty(NodeProperties.VISIBLE)
                        .getValueOrDefault(true);
        return !visible;
    }

    public static final class Styles extends JavaScriptObject {
        protected Styles() {

        }

        public final native void set(String key, Object value)/*-{
            this[key] = value;
        }-*/;
    }

    private JavaScriptObject getElementStyleProperties(int id) {
        StateNode node = registry.getStateTree().getNode(id);
        Styles styles = JavaScriptObject.createObject().cast();
        if (node != null) {
            JsArray<String> names = node
                    .getMap(NodeFeatures.ELEMENT_STYLE_PROPERTIES)
                    .getPropertyNames();
            for (int i = 0; i < names.length(); i++) {
                String name = names.get(i);
                styles.set(name,
                        node.getMap(NodeFeatures.ELEMENT_STYLE_PROPERTIES)
                                .getProperty(name).getValue());

            }
        }
        return styles;
    }

    /**
     * Gets the id of the state node bound to the given DOM element.
     *
     * @param element
     *            the DOM element
     * @return the node id, or {@code -1} if the element is not bound
     */
    public int getNodeId(Element element) {
        StateNode node = registry.getStateTree()
                .getStateNodeForDomNode(DomApi.wrap(element));
        return node == null ? -1 : node.getId();
    }

    /**
     * Registers a callback to be invoked when the DOM node for the state node
     * with the given id is set.
     *
     * @param nodeId
     *            the node id to observe
     * @param callback
     *            the callback to invoke
     */
    @JsMethod(name = "addDomBindingListener")
    public void addDomSetListener(int nodeId, JavaScriptObject callback) {
        registry.getStateTree().getNode(nodeId).addDomNodeSetListener(node -> {
            if (nodeId == node.getId()) {
                NativeFunction function = NativeFunction.create("callback",
                        "callback();");
                function.call(null, callback);
                return true;
            }
            return false;
        });
    }

    /**
     * Methods published to JavaScript on when NOT running in production mode.
     *
     * @param applicationId
     *            the application id provided by the server
     */
    private native void publishDevelopmentModeJavascriptMethods(
            String applicationId, String servletVersion)
    /*-{
        var ap = this;
        var client = $wnd.Vaadin.Flow.clients[applicationId];
        client.isActive = $entry(function() {
            return ap.@com.vaadin.client.ApplicationConnection::isActive()();
        });
        client.getVersionInfo = $entry(function(parameter) {
            return { "flow": servletVersion};
        });
        client.debug = $entry(function() {
            return ap.@com.vaadin.client.ApplicationConnection::debug()();
        });
        client.getNodeInfo = $entry(function(nodeId) {
            return {
                element: ap.@ApplicationConnection::getDomElementByNodeId(*)(nodeId),
                javaClass: ap.@ApplicationConnection::getJavaClass(*)(nodeId),
                hiddenByServer: ap.@ApplicationConnection::isHiddenByServer(*)(nodeId),
                styles: ap.@ApplicationConnection::getElementStyleProperties(*)(nodeId)
            };
        });
    
    }-*/;

    /**
     * Checks if deferred commands are (potentially) still being executed as a
     * result of an update from the server. Returns true if a deferred command
     * might still be executing, false otherwise. This will not work correctly
     * if a deferred command is added in another deferred command.
     * <p>
     * Used by the native "client.isActive" function.
     *
     * @return true if deferred commands are (potentially) being executed, false
     *         otherwise
     */
    private boolean isExecutingDeferredCommands() {
        Scheduler s = Scheduler.get();
        if (s instanceof TrackingScheduler) {
            return ((TrackingScheduler) s).hasWorkQueued();
        } else {
            return false;
        }
    }
}
