ifdef::env-github[:outfilesuffix: .asciidoc]

= Creating A Simple Component Using the Template API

There are multiple ways you can create a component. This tutorial uses the `PolymerTemplate` API with no additional elements or components. For other component tutorials, see:

* <<../tutorial-component-many-elements#,Creating a Component Based on Many Elements>>
* <<../tutorial-component-composite#,Creating a Component Using Existing Components>>
* <<../tutorial-component-container#,Creating a Component Which Can Contain Other Components>>

For tutorials about how to use different template features, see:

* <<tutorial-template-components-in-slot#,Using <slot> in PolymerTemplates>>
* <<tutorial-template-event-handlers#,Handling User Events in a Template>>

This tutorial is based on `demo-hello-world-template` demo from https://github.com/vaadin/hummingbird-demo/ repository.

We'll create a demo, that will be asking a user to input a name and will print a greeting on button click, using the input.

=== Client side

First, we need to define a template with all components:

[source,html]
----
<dom-module id="hello-world">
    <template>
        <div>
            <input type="text" id="inputId">
            <button id="helloButton" on-click="sayHello">Say hello</button>
            <div id="greeting">
                <template is="dom-if" if="[[text]]">
                    Hello [[text]]!
                </template>
                <template is="dom-if" if="[[!text]]">
                    Please enter your name
                </template>
            </div>
        </div>
    </template>
    <script>
        class HelloWorld extends Polymer.Element {
            static get is() {
                return 'hello-world'
            }

            // same method is defined on a server side with the 'event.hello' value as a parameter value.
            // it will always be called after client handlers are executed (after this method in this case)
            sayHello(event) {
                event.hello = this.$.inputId.value;
            }
        }
        customElements.define(HelloWorld.is, HelloWorld);
    </script>
</dom-module>
----

As you can see, this is a Polymer template. All features used in the example are standard Polymer features.
If you're unfamiliar with any of them, please refer to
https://www.polymer-project.org/2.0/docs/about_20[Polymer project documentation page].

In the current demo, we have defined a regular template with regular elements, have specified one-way binding (`\[[text]]`)
and basic declaration for Polymer element in `<script>` class.

Note that there is an event handler `sayHello` that is triggered on `helloButton` click.

Notice that we have not specified the model at all, it will be propagated automatically from the server side.

=== Server side

To be able to use this template you need to create a Java class which extends `PolymerTemplate`,
set its tag name matching the polymer `dom-module` id attribute and add the html imports for Polymer library (`polymer.html`)
and our template:

[source,java]
----
@Tag("hello-world")
@HtmlImport("/polymer/location/polymer.html")
@HtmlImport("/com/example/HelloWorld.html")
public class HelloWorld extends PolymerTemplate<HelloWorldModel> {

    /**
     * Creates the hello world template.
     */
    public HelloWorld() {
        setId("template");
    }

    @EventHandler
    private void sayHello(@EventData("event.hello") String inputValue) {
        // Called from the template click handler
        getModel().setText(inputValue);
    }
}
----

Here we have defined a class with imports, tag, model and event handler.

There is also a model reference, that is defined the following way:
[source,java]
----
/**
 * Model for the template.
 */
public interface HelloWorldModel extends TemplateModel {
    /**
     * Sets the text to show in the template.
     *
     * @param text
     *            the text to show in the template
     */
    void setText(String text);
}
----

====== Imports

In order for a component to be processed correctly, we need to

* import a Polymer library

The `/polymer/location/polymer.html` is a link to Polymer library that should be imported in order to have the
functionality working.

[NOTE] You should take care about proper handling of the polymer template file URL, it should be available via URL.

[NOTE] To get `polymer.html` into your project, you can use one of the ways provided by
https://www.polymer-project.org/2.0/start/install-2-0[official Polymer page] or use Maven plugins, such as
https://github.com/eirslett/frontend-maven-plugin[frontend-maven-plugin]

The latter way was used to create this example, you can reference
https://github.com/vaadin/hummingbird-demo/[GitHub page] of a demo for more details.

* bind a Java class with the template, by specifying `@HtmlImport` with path to a template

The `/com/example/HelloWorld.html` is the URL of the polymer template file declared earlier.

[NOTE] Java class name and template file name doesn't have to match each other.

====== Tag

The tag corresponds to `<dom-module id="hello-world">` id attribute, it sets the tag value to current component.

====== Model

Model describes all properties that are passed to the html template and used on the client side.
The model is simple Java interface, extending `TemplateModel` class and having getter and/or setter methods
for properties.
Model can be accessed via `getModel()` method after it's specified as a generic type of `PolymerTemplate` class.

====== Event handler

In this demo, there are two event handlers, one on the client side, one on the server side (a method, annotated as `@EventHandler`).
The framework guarantees that server will handle the event after the client.

If no client event handler is needed, it can be omitted, the event will be handled on the server side still.

In this demo, client event is used to add extra property to an `event` object. This property is retrieved on a server side
with help of the following construction: `@EventData("event.hello") String inputValue`

=== Usage in code

You can use `HelloWorld` like any other component.

[source,java]
----
HelloWorld hello = new HelloWorld();

Div layout = new Div();
layout.add(hello);
----
