ifdef::env-github[:outfilesuffix: .asciidoc]
= Binding Model Data in a PolymerTemplate

At the core of `PolymerTemplate` is the way model values are bound to different parts of the element tree defined by the template.
To get started with using templates and learn how to set model values, see <<tutorial-template-basic#,Creating A Simple Component Using the Template API>>.

== Binding Text Content

The value of a model property can be used as the text content of an element using `\[[propertyName]]` inside a tag.

.Sample HTML Template
[source,html]
----
<dom-module id="my-template">
    <template>
        <div>[[hostProperty]]</div>
    </template>
    <script>
         class MyTemplate extends Polymer.Element {
           static get is() {return 'my-template'}
         }
         customElements.define(MyTemplate.is, MyTemplate);
    </script>
</dom-module>
----

For the server-side sample see: <<server-side-sample,Server-side model sample code>>

== Binding Property Values

You can set an element property value based on a model by using the property name in attribute form (dash-case not camelCase):

[source,html]
----
<dom-module id="my-template">
<template>
    <my-element my-property="[[hostProperty]]">
</template>
...
</dom-module>
----

This example binds to the target property, myProperty on <my-element>.

[NOTE]
`name="\[[binding]]"` defines that the element _property_ named `name` should get it's value
from the model property named `binding`, whereas `name="binding"` (i.e. without brackets)
defines that the element _attribute_ named `name` should have the value `binding`
regardless of any value in the model.

There are a handful of common native element properties that Polymer can't data-bind to directly, because the binding causes issues on one or more browsers and you need to use attribute bindings instead.
For more information on these properties see: https://www.polymer-project.org/2.0/docs/devguide/data-binding#native-binding[Native properties that don't support property binding]

== Binding Attribute Values

A binding written as `<div something="\[[hostProperty]]"></div>` is bound to the _property_ `something` because the property can typically be changed on the fly while the attribute is often used only for the initial value.

When you want to explicitly bind to an attribute instead, use the attribute name followed by $:

[source,html]
----
<dom-module id="my-template">
    <template>
        <div something$="[[hostProperty]]"></div>
    </template>
    ...
</dom-module>
----

or

[source,html]
----
<dom-module id="my-template">
    <template>
        <a href$="[[hostProperty]]"></a>
    </template>
    ...
</dom-module>
----

[NOTE]
--
Text surrounded by double curly bracket {{ }} or double square bracket [[ ]] delimiters identify the host data being bound.

* Double-curly brackets support both upward and downward data flow. see <<two-way-binding,Two-way binding>>.

* Double square brackets are one-way, and support only downward data flow.
--

[[two-way-binding]]


[[server-side-sample]]
=== Server-side model sample code

Here is the server-side sample for tutorial html templates.

.PolymerTemplate class
[source,java]
----
@Tag("my-template")
@HtmlImport("/com/example/PolymerBinding.html")
public class PolymerBindingTemplate extends PolymerTemplate<BindingModel> {

    public PolymerBindingTemplate() {
        getModel().setHostProperty("Bound property");
    }
}
----

.TemplateModel sample
[source,java]
----
public interface BindingModel extends TemplateModel {
    void setHostProperty(String propertyValue);
    String getHostProperty();
}
----
