ifdef::env-github[:outfilesuffix: .asciidoc]
= Using Events with Components

Your component class can provide an API for adding event listeners using the event bus provided by the `Component` base class.

== Defining an Event

Events used with the event bus should extend `ComponentEvent`.
The base type is parameterized with the type of the component firing the event, so that `getSource()` can automatically return the right component type.

[source,java]
----
public class ChangeEvent extends ComponentEvent<TextField> {
    public ChangeEvent(TextField source, boolean fromClient) {
        super(source, fromClient);
    }
}
----

Event listeners are of the type `java.util.function.Consumer<EventType>`. You don't need to implement a separate method for removing an event listener. Instead, the method for adding a listener returns a handle that can be used for removing the listener.

[source,java]
----
@Tag("input")
public class TextField extends Component {
    public EventRegistrationHandle addChangeListener(
            Consumer<ChangeEvent> listener) {
        return addListener(ChangeEvent.class, listener);
    }

    // Other component methods omitted
}
----

The component can then be used like this.

[source,java]
----
TextField textField = new TextField();
EventRegistrationHandle registration = textField
        .addChangeListener(e -> System.out.println("Event fired"));

// In some other part of the code
registration.remove();
----

== Firing Events From the Server

You can fire an event on the server by creating the event instance and passing it to the `fireEvent` method.
The event should be created with `false` as the second constructor parameter to indicate that the event does not come from the client.

[source,java]
----
@Tag("input")
public class TextField extends Component {

    public void setValue(String value) {
        getElement().setAttribute("value", value);
        fireEvent(new ChangeEvent(this, false));
    }

    // Other component methods omitted
}
----

== Firing Events From the Client

You can also connect a component event to a DOM event that will be fired by the element in the browser.
To do this, you only need to tell the framework the name of the DOM event to listen to by adding a `@DomEvent` annotation to your event class.
The framework will automatically add a DOM listener to the element when a listener is added to the component.

[source,java]
----
@DomEvent("change")
public class ChangeEvent extends ComponentEvent<TextField> {
    public ChangeEvent(TextField source, boolean fromClient) {
        super(source, fromClient);
    }
}
----

=== Adding Event Data

An event can also include additional information about what has happened, e.g. which mouse button was used for a click event.
If you use `@DomEvent`, any additional constructor parameters should have an `@EventData` annotation that tells the framework what data to send from the browser.

[source,java]
----
@DomEvent("click")
public class ClickEvent extends ComponentEvent<Button> {
    private final int button;

    public ClickEvent(Button source, boolean fromClient,
            @EventData("event.button") int button) {
        super(source, fromClient);
        this.button = button;
    }

    public int getButton() {
        return button;
    }
}
----

The `@EventData` definition is run as JavaScript in the browser with the DOM event available as `event` and the element to which the listener was added available as `element`.

[TIP]
See https://developer.mozilla.org/en-US/docs/Web/API/Event for an overview of the standard DOM events and their properties.
