ifdef::env-github[:outfilesuffix: .asciidoc]
= Element Properties and Attributes
:toc:
You can change property and attribute values for server-side Elements.

[WARNING]
Values updated in the browser are by default not sent back to the server.
See the <<tutorial-user-input#,Retrieving User Input>> tutorial to learn how to get data back to the server.

== Attributes
Attributes are mainly used for initial configuration of an element.
Attribute values are always stored as strings.

[source,java]
----
Element nameField = ElementFactory.createInput();
nameField.setAttribute("id", "nameField");
nameField.setAttribute("placeholder", "John Doe");
nameField.setAttribute("autofocus", "");
----
The above example expressed as HTML would look like `<input id=nameField placeholder="John Doe" autofocus>`.

You can also investigate and manipulate attributes that have already been set.
[source,java]
----
// "John Doe"
String placeholder = nameField.getAttribute("placeholder");

// true
nameField.hasAttribute("autofocus");

nameField.removeAttribute("autofocus");

// ["id", "placeholder"]
nameField.getAttributeNames().toArray();
----

== Properties

Properties are mainly used for dynamically changing the settings of an element after it has been initialized.
In the browser, any JavaScript value can be used as a property value.
You can use different variations of the `setProperty` method for setting a property value as `String`, `boolean`, `double` and `JsonValue`.

[source,java]
----
Element element = ElementFactory.createInput();
element.setProperty("value", "42.2");
----

Similarly, the value of a property can be fetched as any of those types using different `getProperty` method variations.
The value will be converted according to JavaScript type coercion rules if it is fetched as some other type than how it was set.
For instance, a property set as a non-empty string will result in `true` if fetched as a boolean.

[source,java]
----
// true, since any non-empty string is true in JavaScript
boolean helloBoolean = element.getProperty("value", true);

// 42, string is parsed to a JS number and truncated to an int
int helloInt = element.getProperty("value", 0);
----

[WARNING]
There are many cases where you can use either an attribute or a property with the same name for the same effect.
In some cases only one of them works, in other cases the attribute is considered when the element is initialized, but after initialization only the property is effective.
Please check documentation specific to the element you're using to find out whether a feature should be configured using a property or an attribute.

[[classList]]
== Class / ClassList / ClassName

Class names for elements can be added, removed and inspected using the collection returned by the `getClassList` method.
You cannot modify the _classList_ or _className_ properties directly using `setProperty`.
Using `element.getProperty("className")` you can get all of the set classes as a concatenated string.

[source,java]
----
element.getClassList().add("error");
element.getClassList().add("critical");
element.getClassList().remove("primary");

element.getProperty("className"); // will return "error critical".
----

[NOTE]
You can set the element's _class_ attribute using `element.setAttribute("class", "foo bar");`.
This will clear any previously set _classList_ property.
You can get the element's class attribute using `element.getAttribute('class')` which will return the contents of the _classList_ property as a single concatenated string.

[[style]]
== Style object

Element inline styles can be set using the `Style` object returned by `element.getStyle()`.
Style property names should always be in the camelCase format, e.g. `backgroundColor`
instead of `background-color`.

[source,java]
----
element.getStyle().set("color", "red");
// Note the camelCase, not dash - separated
element.getStyle().set("fontWeight", "bold");

// Note the camelCase, not dash - separated
element.getStyle().remove("backgroundColor");

element.getStyle().has("cursor");
----

[NOTE]
You cannot set the element's _style_ attribute using the `element.setAttribute` method.
However you can use `element.getAttribute('style')` to get all the style rules in a single concatenated string.

[[textContent]]
== TextContent

The element's _textContent_ property can be set using the `setTextContent` method.
Note that this removes all children of the element and replaces them with a single text node with the given value.

[TIP]
`ElementFactory` provides helpers for creating elements with a given text content.

[source,java]
----
Element element = ElementFactory.createDiv("Hello world");  // <div>Hello world</div>

element.appendChild(ElementFactory.createSpan()); // <div>Hello world<span></span></div>

element.setTextContent("Replacement text"); // <div>Replacement text</div>
----

You can fetch the element's _textContent_ with the `getTextContent` method,
but note that it returns a concatenation of the _textContent_
property values of the element and all its child nodes. The child nodes are iterated recursively.

[source,java]
----
element.setTextContent("Welcome back ");

Element name = ElementFactory.createStrong("Rudolph Reindeer");
element.appendChild(name);

element.getTextContent(); // will return "Welcome back Rudolph Reindeer"
----
