= Adding Components to a Template

Here is the content of the HTML template file which has a placeholder `div` element with a `"content"` identifier. This element is mapped to a `Div` component in Java code below to set a `Component` as a child for it.

[source,html]
----
<div>
    <div id="header">Main page</div>
    <div id="content"></div>
    <hr>
    <div id="footer">
        <a href="mailto:someone@example.com?Subject=Hello%20again" target="_top">Send Mail</a>
    </div>
</div>
----

You can implement the method that sets a `Component` as the content for your template component.

[source,java]
----
public class MainPage extends Template {

    @Id("content")
    private Div container;

    public void setContent(Component content) {
        container.removeAll();
        container.add(content);
    }
}
----

Now you can set any `Component` as a content for the `MainPage` class:

[source,java]
----
MainPage page = new MainPage();
page.setContent(new Label("Hello!"));
----

[NOTE]
An alternative way of implementing `MainPage` would be to iterate the Element tree and using `Element.appendChild`. Mapping an element to a `Component` is in many cases easier and adds no significant overhead.

[TIP]
You can use only add new elements to template elements without children. In the example above the `"content"` element is eligible for modification but the `"header"` element is not.
