ifdef::env-github[:outfilesuffix: .asciidoc]
= Handling User Events in a Template

== Client Side Event Handlers
Template defines a special syntax `(event-name)="javascriptCode"` for attaching client side event handlers to elements:

[source,html]
----
<button (click)="window.alert('Hello');">Say hello</button>
----

Clicking on the `<button>` will now show an alert in the browser. You can listen to any event using the `(event-name)` syntax, it does not matter if it is a built-in browser event or a custom event from e.g. a web component.

== Server Side Event Handlers
To handle a DOM event in a template on the server side, you have two options:

1. Use a client side listener which calls the server, e.g. `(event)=$server.myEventHandler(myParameters)` to invoke the `myEventHandler` method in the server side `Template` class.
2. Find a reference to the element in the server `Template` class and attach a listener. This is similar to what is done in <<tutorial-event-listener#,Listening to User Events>>

=== Event Listener in the HTML Template
In the following template a click listener is attached to the button and the event handler calls the `sayHello` method on the server:

[source,html]
----
<div>
  <input id="name" />
  <button (click)="$server.sayHello(name.value)">Say hello</button>
  <span>{{helloText}}</span>
</div>
----

[NOTE]
We can use `name.value` because the `<input>` element has `id="name"` and the browser makes these elements available in the global namespace using their id.

The server side template class defines the published `sayHello` method using the `@EventHandler` annotation:

[source,java]
----
public class MyTemplate extends Template {
  public interface MyModel extends TemplateModel {
      public void setHelloText(String helloText);
  }
  @Override
  public MyModel getModel() {
      return (MyModel) super.getModel();
  }

  @EventHandler
  private void sayHello(String name) {
    getModel().setHelloText("Hello " + name);
  }
}
----

The `sayHello` method is invoked whenever `$server.sayHello` is called on the client side and the given parameters will be passed to the method on the server. In this case the event handler updates the template model so that a "Hello <name>" message is shown.

[NOTE]
Only `String`, `int`, `Integer`, `double`, `Double`, `boolean`, `Boolean`, `JsonValue` and arrays of all those types are supported parameter types.
[NOTE]
The `@EventHandler` method can have any access modifier (`private`/`protected`/`public`) but must return `void`.
[NOTE]
The `$server` variable is only available in template event handlers.

=== Event Listener in the Server Side Java Class
If you use a server side event listener, you can use the same template as above but without any listener code:

[source,html]
----
<div>
  <input id="name" />
  <button id="button">Say hello</button>
  <span>{{helloText}}</span>
</div>
----

The server side `Template` will instead map the `<button>` element to a `Button` component and add a click listener to it:

[source,java]
----
public class MyTemplate extends Template {
  public interface MyModel extends TemplateModel {
      public void setHelloText(String helloText);
  }
  @Override
  public MyModel getModel() {
      return (MyModel) super.getModel();
  }

  @Id("button")
  private Button button;
  @Id("name")
  private Input name;

  public MyTemplate() {
    button.addClickListener(e->{
      getModel().setHelloText("Hello " + name.getValue());
    });
  }
}
----

The `@Id` annotation is used here to map a component to an element defined in the template with an appropriate identifier.
See <<tutorial-template-components#,Adding Components to a Template>> for the details.
