/*
 * Copyright 2000-2026 Vaadin Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

import type { ApplicationConfiguration, ApplicationConnection } from './clientApi';

/**
 * Builds the per-application client API object published on
 * `window.Vaadin.Flow.clients[appId]`.
 *
 * This is the TypeScript replacement for the JSNI `publishJavascriptMethods` /
 * `publishDevelopmentModeJavascriptMethods` blocks in
 * com.vaadin.client.ApplicationConnection: it delegates to the methods of the
 * {@link ApplicationConnection} instance. Those blocks wrap every published
 * function in `$entry`; the port has no equivalent, as the engine is plain
 * JavaScript.
 *
 * Called by ApplicationConnection.create with the constructed instance. The live
 * page still runs the GWT engine, so the JSNI publication is what actually
 * populates `window.Vaadin.Flow.clients` today; removing it is part of the
 * cutover that makes the bootstrap start this engine instead.
 *
 * @param applicationConnection - the engine to publish
 * @param configuration - the application configuration, which supplies the
 *          application id the client is published under, whether the client runs
 *          in production mode, whether request timing info should be made
 *          available, and the web component tags exported by this UI
 */
export function publishClient(
  applicationConnection: ApplicationConnection,
  configuration: ApplicationConfiguration
): void {
  const ac = applicationConnection;
  const productionMode = configuration.isProductionMode();

  // The clients[] key is the application id with the autogenerated window-name
  // suffix removed (the TestBench id). No 'u' flag: the bundle is transpiled to
  // ES5 for the (old) HtmlUnit used by GwtTests, which rejects the unicode flag.
  const applicationId = configuration.getApplicationId().replace(/-\d+$/, '');

  const client: Record<string, unknown> = {
    isActive: () => ac.isActive(),
    getByNodeId: (nodeId: number) => ac.getDomElementByNodeId(nodeId),
    getNodeId: (element: Element) => ac.getNodeId(element),
    getUIId: () => ac.getUIId(),
    addDomBindingListener: (nodeId: number, callback: () => void) => ac.addDomSetListener(nodeId, callback),
    productionMode,
    poll: () => ac.poll(),
    connectWebComponent: (eventData: object) => ac.connectWebComponent(eventData),
    resolveUri: (uri: string) => ac.resolveUri(uri),
    sendEventMessage: (nodeId: number, eventType: string, eventData: object | null) =>
      ac.sendEventMessage(nodeId, eventType, eventData),
    initializing: false,
    exportedWebComponents: configuration.getExportedWebComponents()
  };

  if (configuration.isRequestTiming()) {
    client.getProfilingData = () => ac.getProfilingData();
  }

  if (!productionMode) {
    // The Java block also re-publishes client.isActive here, with the same
    // function it published above; the port publishes it once.
    client.getVersionInfo = (_parameter?: unknown) => ({ flow: configuration.getServletVersion() });
    client.debug = () => ac.debug();
    client.getNodeInfo = (nodeId: number) => ({
      element: ac.getDomElementByNodeId(nodeId),
      javaClass: ac.getJavaClass(nodeId),
      hiddenByServer: ac.isHiddenByServer(nodeId),
      styles: ac.getElementStyleProperties(nodeId)
    });
  }

  const clients = (
    window as unknown as {
      Vaadin: { Flow: { clients: Record<string, unknown> } };
    }
  ).Vaadin.Flow.clients;
  clients[applicationId] = client;
}
