= Building a Hello World Application

The simplest possible Hello World application displays the text "Hello world" on the screen and does nothing else. To accomplish this you need two things:

* A component containing our UI elements
* A servlet handling the rendering of the component

Let's start from the View class:

[source,java]
----
@Route("")
public class HelloWorld extends Div {
    public HelloWorld() {
      setText("Hello world");
    }
}
----

The main purpose of this div is to populate the UI with components. In this case the class extends the very simple `Div` component (corresponds to a `<div>` in the browser) and you can use its `setText` method to show the message.

[TIP]
The `com.vaadin.flow.html` package contains a number of commonly used components. You can also extend `HtmlComponent` to create any custom component.

To get the component to show up in the browser, you need to add a servlet and configure it to show the given view for the root URL:

[source,java]
----
@WebServlet(urlPatterns = "/*", name = "HelloWorldServlet")
@VaadinServletConfiguration(productionMode = false)
public class HelloWorldServlet extends VaadinServlet {
}
----

Your servlet will listen for HTTP requests to all paths (`"/*"`) and serve the `HelloWorld` view when the root URL is requested (`setRoute("",...)`). Deploy the application to a servlet container, and open the URL (typically http://localhost:8080/<name-of-project>) to see the "Hello world" text.

For more information about defining routes, see  <<tutorial-routing-annotation#,Defining Routes With @Route>>.
