/*
 * Copyright 2000-2026 Vaadin Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

import type { ApplicationConfiguration, ApplicationConnection } from './gwtExports';

/**
 * Builds the per-application client API object published on
 * `window.Vaadin.Flow.clients[appId]`.
 *
 * This is the TypeScript replacement for the JSNI `publishJavascriptMethods` /
 * `publishDevelopmentModeJavascriptMethods` blocks in
 * `com.vaadin.client.ApplicationConnection`: it delegates to the exported
 * methods of the (GWT-constructed) `ApplicationConnection` instance. The
 * exported methods carry the GWT entry-point semantics, so no explicit `$entry`
 * wrapping is needed here.
 *
 * Not yet wired into the bootstrap — see `MIGRATION_STRATEGY.md`. The handoff
 * that calls this with the constructed instance, and the removal of the JSNI
 * publication, is a separate step.
 */
export function publishClient(
  applicationConnection: ApplicationConnection,
  configuration: ApplicationConfiguration
): void {
  const ac = applicationConnection;
  const productionMode = configuration.isProductionMode();

  // The clients[] key is the application id with the autogenerated window-name
  // suffix removed (the TestBench id).
  const applicationId = configuration.getApplicationId().replace(/-\d+$/u, '');

  const client: Record<string, unknown> = {
    isActive: () => ac.isActive(),
    getByNodeId: (nodeId: number) => ac.getByNodeId(nodeId),
    getNodeId: (element: Element) => ac.getNodeId(element),
    getUIId: () => ac.getUIId(),
    addDomBindingListener: (nodeId: number, callback: () => void) => ac.addDomBindingListener(nodeId, callback),
    productionMode,
    poll: () => ac.poll(),
    connectWebComponent: (eventData: object) => ac.connectWebComponent(eventData),
    resolveUri: (uri: string) => ac.resolveUri(uri),
    sendEventMessage: (nodeId: number, eventType: string, eventData: object | null) =>
      ac.sendEventMessage(nodeId, eventType, eventData),
    initializing: false,
    exportedWebComponents: configuration.getExportedWebComponents()
  };

  if (configuration.isRequestTiming()) {
    client.getProfilingData = () => ac.getProfilingData();
  }

  if (!productionMode) {
    client.getVersionInfo = () => ({ flow: configuration.getServletVersion() });
    client.debug = () => ac.debug();
    client.getNodeInfo = (nodeId: number) => ({
      element: ac.getByNodeId(nodeId),
      javaClass: ac.getJavaClass(nodeId),
      hiddenByServer: ac.isHiddenByServer(nodeId),
      styles: ac.getElementStyleProperties(nodeId)
    });
  }

  const clients = (
    window as unknown as {
      Vaadin: { Flow: { clients: Record<string, unknown> } };
    }
  ).Vaadin.Flow.clients;
  clients[applicationId] = client;
}
