<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-cdi-parent</artifactId>
    <version>16.1-SNAPSHOT</version>
  </parent>

  <artifactId>vaadin-cdi-itest</artifactId>

  <properties>
    <maven.deploy.skip>true</maven.deploy.skip>
    <surefire.groups/>
    <surefire.excludedGroups>com.vaadin.cdi.itest.SlowTests</surefire.excludedGroups>
    <apache-tomcat.version>11.0.8</apache-tomcat.version>
    <apache-tomee.version>10.1.0</apache-tomee.version>
    <wildfly.version>39.0.0.Final</wildfly.version>
    <openliberty.version>25.0.0.6</openliberty.version>
    <openliberty.template>jakartaee10</openliberty.template>
    <openliberty.runtimeArtifactGroupId>io.openliberty</openliberty.runtimeArtifactGroupId>
    <maven-dependency-plugin.version>3.8.1</maven-dependency-plugin.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>vaadin-cdi</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>jakarta.enterprise</groupId>
      <artifactId>jakarta.enterprise.cdi-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>jakarta.annotation</groupId>
      <artifactId>jakarta.annotation-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>jakarta.enterprise.concurrent</groupId>
      <artifactId>jakarta.enterprise.concurrent-api</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- Vaadin flow -->
    <dependency>
      <groupId>com.vaadin</groupId>
      <artifactId>flow-server</artifactId>
    </dependency>
    <dependency>
      <groupId>com.vaadin</groupId>
      <artifactId>flow-client</artifactId>
    </dependency>
    <dependency>
      <groupId>com.vaadin</groupId>
      <artifactId>flow-html-components</artifactId>
    </dependency>
    <dependency>
      <groupId>com.vaadin</groupId>
      <artifactId>flow-polymer-template</artifactId>
    </dependency>
    <!-- Test dependencies -->
    <dependency>
      <groupId>org.jboss.arquillian.junit</groupId>
      <artifactId>arquillian-junit-container</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jboss.shrinkwrap.resolver</groupId>
      <artifactId>shrinkwrap-resolver-impl-maven</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jboss.shrinkwrap.descriptors</groupId>
      <artifactId>shrinkwrap-descriptors-impl-javaee</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.vaadin</groupId>
      <artifactId>flow-test-util</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.lucee</groupId>
      <artifactId>jcip-annotations</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <pluginRepositories>
    <pluginRepository>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <id>vaadin-prereleases</id>
      <url>https://maven.vaadin.com/vaadin-prereleases</url>
    </pluginRepository>
  </pluginRepositories>

  <build>
    <plugins>
      <plugin>
        <groupId>com.vaadin</groupId>
        <artifactId>flow-maven-plugin</artifactId>
        <version>${vaadin.flow.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>prepare-frontend</goal>
              <goal>build-frontend</goal>
            </goals>
            <phase>compile</phase>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <!--
                JBoss shrinkwrap archive provider builds war based on pom file,
                so generate effective pom to record any command-line property
                overrides.
                -->
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-help-plugin</artifactId>
        <version>3.5.1</version>
        <configuration>
          <output>${project.build.directory}/effective-pom.xml</output>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>effective-pom</goal>
            </goals>
            <phase>generate-test-resources</phase>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>tomee</id>
      <dependencies>
        <dependency>
          <groupId>org.apache.tomee</groupId>
          <artifactId>arquillian-tomee-remote</artifactId>
          <version>${apache-tomee.version}</version>
          <scope>test</scope>
        </dependency>
        <dependency>
          <groupId>org.apache.tomee</groupId>
          <artifactId>apache-tomee</artifactId>
          <version>${apache-tomee.version}</version>
          <classifier>webprofile</classifier>
          <type>zip</type>
          <scope>test</scope>
        </dependency>
      </dependencies>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>${maven.surefire.plugin.version}</version>
            <configuration>
              <excludedGroups>${surefire.excludedGroups}</excludedGroups>
              <groups>${surefire.groups}</groups>
              <systemPropertyVariables>
                <tomee.host>0.0.0.0</tomee.host>
              </systemPropertyVariables>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>wildfly</id>
      <dependencies>
        <dependency>
          <groupId>org.wildfly.arquillian</groupId>
          <artifactId>wildfly-arquillian-container-managed</artifactId>
          <version>5.0.1.Final</version>
          <scope>test</scope>
        </dependency>
        <dependency>
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-simple</artifactId>
          <scope>test</scope>
        </dependency>
      </dependencies>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <version>${maven-dependency-plugin.version}</version>
            <executions>
              <execution>
                <id>unpack</id>
                <goals>
                  <goal>unpack</goal>
                </goals>
                <phase>process-test-classes</phase>
                <configuration>
                  <artifactItems>
                    <artifactItem>
                      <groupId>org.wildfly</groupId>
                      <artifactId>wildfly-preview-dist</artifactId>
                      <version>${wildfly.version}</version>
                      <type>zip</type>
                      <outputDirectory>target</outputDirectory>
                    </artifactItem>
                  </artifactItems>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>${maven.surefire.plugin.version}</version>
            <configuration>
              <excludedGroups>${surefire.excludedGroups}</excludedGroups>
              <groups>${surefire.groups}</groups>
              <systemPropertyVariables>
                <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                <jboss.home>${project.build.directory}/wildfly-preview-${wildfly.version}</jboss.home>
                <arquillian.launch>wildfly</arquillian.launch>
              </systemPropertyVariables>
              <redirectTestOutputToFile>false</redirectTestOutputToFile>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>payara</id>
      <dependencies>
        <dependency>
          <groupId>fish.payara.arquillian</groupId>
          <artifactId>arquillian-payara-server-managed</artifactId>
          <version>3.1</version>
          <scope>test</scope>
        </dependency>
        <dependency>
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-simple</artifactId>
          <scope>runtime</scope>
        </dependency>
      </dependencies>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <version>${maven-dependency-plugin.version}</version>
            <executions>
              <execution>
                <id>unpack</id>
                <goals>
                  <goal>unpack</goal>
                </goals>
                <phase>process-test-classes</phase>
                <configuration>
                  <artifactItems>
                    <artifactItem>
                      <groupId>fish.payara.distributions</groupId>
                      <artifactId>payara</artifactId>
                      <version>6.2025.6</version>
                      <type>zip</type>
                      <overWrite>false</overWrite>
                      <outputDirectory>target</outputDirectory>
                    </artifactItem>
                  </artifactItems>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>${maven.surefire.plugin.version}</version>
            <configuration>
              <excludedGroups>${surefire.excludedGroups}</excludedGroups>
              <groups>${surefire.groups}</groups>
              <systemPropertyVariables>
                <payara.home>${project.build.directory}/payara6</payara.home>
                <arquillian.launch>payara</arquillian.launch>
                <vaadin.bowerMode>true</vaadin.bowerMode>
              </systemPropertyVariables>
              <redirectTestOutputToFile>false</redirectTestOutputToFile>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>liberty</id>
      <dependencies>
        <dependency>
          <groupId>io.openliberty.arquillian</groupId>
          <artifactId>arquillian-liberty-managed-jakarta-junit</artifactId>
          <version>2.1.4</version>
          <type>pom</type>
        </dependency>
      </dependencies>
      <build>
        <plugins>
          <plugin>
            <groupId>io.openliberty.tools</groupId>
            <artifactId>liberty-maven-plugin</artifactId>
            <version>3.11.4</version>
            <executions>
              <execution>
                <id>create-server</id>
                <goals>
                  <goal>create</goal>
                  <goal>install-feature</goal>
                  <goal>configure-arquillian</goal>
                </goals>
                <phase>process-test-classes</phase>
                <configuration>
                  <runtimeArtifact>
                    <groupId>${openliberty.runtimeArtifactGroupId}</groupId>
                    <artifactId>openliberty-runtime</artifactId>
                    <version>${openliberty.version}</version>
                    <type>zip</type>
                  </runtimeArtifact>
                  <useOpenLiberty>true</useOpenLiberty>
                  <template>${openliberty.template}</template>
                  <features>
                    <feature>jakartaee-10.0</feature>
                    <feature>localConnector-1.0</feature>
                  </features>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <!-- liberty-maven-plugin:install-feature goal installs new features but does not update
                         server.xml file. localConnector-1.0 needs to be present in server.xml for Arquillian -->
            <artifactId>maven-antrun-plugin</artifactId>
            <version>3.1.0</version>
            <executions>
              <execution>
                <goals>
                  <goal>run</goal>
                </goals>
                <phase>process-test-classes</phase>
                <configuration>
                  <target>
                    <copy file="${project.build.testSourceDirectory}/../resources/liberty/server.xml" overwrite="true" tofile="${project.build.directory}/liberty/wlp/usr/servers/defaultServer/server.xml"/>
                  </target>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>${maven.surefire.plugin.version}</version>
            <configuration>
              <excludedGroups>${surefire.excludedGroups}</excludedGroups>
              <groups>${surefire.groups}</groups>
              <systemPropertyVariables>
                <arquillian.launch>liberty_managed</arquillian.launch>
              </systemPropertyVariables>
              <redirectTestOutputToFile>false</redirectTestOutputToFile>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>tomcat-weld</id>
      <dependencies>
        <dependency>
          <groupId>org.jboss.arquillian.container</groupId>
          <artifactId>arquillian-tomcat-managed-10</artifactId>
          <version>1.2.3.Final</version>
          <scope>test</scope>
        </dependency>
        <!-- Weld servlet for testing CDI injections -->
        <dependency>
          <groupId>org.jboss.weld.servlet</groupId>
          <artifactId>weld-servlet-shaded</artifactId>
          <version>${weld.version}</version>
          <scope>test</scope>
        </dependency>
        <dependency>
          <groupId>jakarta.enterprise.concurrent</groupId>
          <artifactId>jakarta.enterprise.concurrent-api</artifactId>
        </dependency>
      </dependencies>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <version>${maven-dependency-plugin.version}</version>
            <executions>
              <execution>
                <id>unpack</id>
                <goals>
                  <goal>unpack</goal>
                </goals>
                <phase>process-test-classes</phase>
                <configuration>
                  <artifactItems>
                    <artifactItem>
                      <groupId>org.apache.tomcat</groupId>
                      <artifactId>tomcat</artifactId>
                      <version>${apache-tomcat.version}</version>
                      <type>zip</type>
                      <outputDirectory>target</outputDirectory>
                    </artifactItem>
                  </artifactItems>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-resources-plugin</artifactId>
            <version>3.3.1</version>
            <executions>
              <execution>
                <id>setup-tomcat-users</id>
                <goals>
                  <goal>copy-resources</goal>
                </goals>
                <phase>process-test-classes</phase>
                <configuration>
                  <resources>
                    <resource>
                      <directory>${project.basedir}/src/test/resources/tomcat</directory>
                      <includes>
                        <include>tomcat-users.xml</include>
                      </includes>
                    </resource>
                  </resources>
                  <outputDirectory>${project.build.directory}/apache-tomcat-${apache-tomcat.version}/conf</outputDirectory>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>${maven.surefire.plugin.version}</version>
            <configuration>
              <excludedGroups>com.vaadin.cdi.itest.NeedsCDICompliantContainer,${surefire.excludedGroups}</excludedGroups>
              <groups>${surefire.groups}</groups>
              <systemPropertyVariables>
                <arquillian.launch>tomcat-weld</arquillian.launch>
                <catalina.home>${project.build.directory}/apache-tomcat-${apache-tomcat.version}</catalina.home>
              </systemPropertyVariables>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>slowtests</id>
      <properties>
        <surefire.excludedGroups/>
        <surefire.groups>com.vaadin.cdi.itest.SlowTests</surefire.groups>
      </properties>
    </profile>
  </profiles>
</project>
