/******************************************************************************
 * This file is auto-generated by Vaadin.
 * It defines a basic routing configuration that can be extended with newly
 * added routes.
 * If you want to use the File System-based routing autoconfiguration, you need:
 *    - remove the current routes initialisation and exports;
 *    - uncomment the routes initialisation below;
 *    - run "npm i @vaadin/hilla-file-router" to install Vite plugin
 *    - add the "vitePluginFileSystemRouter" Vite plugin into vite.config.ts:
 *        const customConfig: UserConfigFn = (env) => ({
 *           plugins: [vitePluginFileSystemRouter()]
 *        });
 ******************************************************************************/
import { createBrowserRouter, RouteObject } from 'react-router-dom';
import { serverSideRoutes } from "Frontend/generated/flow/Flow";

export const routes = [
  ...serverSideRoutes
] as RouteObject[];

export default createBrowserRouter(routes);

// An example of File System-based routing auto-configuration
// import views from 'Frontend/generated/views.js';
// views.children?.push(...serverSideRoutes);
// export const routes = views;
// export default createBrowserRouter(views, {basename: new URL(document.baseURI).pathname });
