#!/usr/bin/env node
/**
 * @license
 * Copyright (c) 2015 The Polymer Project Authors. All rights reserved.
 * This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 * The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 * The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 * Code distributed by Google as part of the polymer project is also
 * subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
 */

'use strict';

var resolve = require('resolve');
var path = require('path');

process.title = 'polyserve';

resolve('polyserve', {basedir: process.cwd()}, function(error, libpath) {
  var clipath = libpath ? path.resolve(libpath, '../cli') : '../lib/cli';
  var cli = require(clipath);
  cli.run(process.argv)
    .catch(function(e) {
      console.error(e);
      process.exit(69);
    });
});
