/*
 * Copyright 2000-2018 Vaadin Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.vaadin.flow.component.polymertemplate;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

import com.google.common.base.Predicates;
import com.google.javascript.jscomp.NodeUtil;
import com.google.javascript.jscomp.SourceFile;
import com.google.javascript.jscomp.parsing.Config;
import com.google.javascript.jscomp.parsing.ParserRunner;
import com.google.javascript.rhino.ErrorReporter;
import com.google.javascript.rhino.Node;
import com.google.javascript.rhino.SimpleErrorReporter;
import com.google.javascript.rhino.StaticSourceFile;

import elemental.json.Json;
import elemental.json.JsonArray;
import elemental.json.JsonObject;
import elemental.json.JsonType;

/**
 * Parse statistics data provided by webpack.
 *
 * @see NpmTemplateParser
 *
 * @author Vaadin Ltd
 * @since
 *
 */
public final class BundleParser {

    private static Config config = ParserRunner
            .createConfig(Config.LanguageMode.ECMASCRIPT6, null,
                    Config.StrictMode.STRICT);

    private static final String TEMPLATE_TAG_NAME = "template";

    private BundleParser() {
    }

    /**
     * Get a JsonObject from the statistics data json string generated by
     * webpack.
     *
     * @param fileName
     *            name of the file to get from the json
     * @param statistics
     *            statistics json as a String
     * @return JsonObject for the file statistic
     */
    public static JsonObject getStatisticsJson(String fileName,
            String statistics) {
        return getObjectByFileName(fileName, Json.parse(statistics));
    }

    /**
     * Get the template element for given statistics file object.
     *
     * @param statisticsJson
     *            webpack profile json object
     * @return template element for the sources of the given file sources
     */
    public static Element parseTemplateElement(String name, JsonObject statisticsJson) {
        return parseTemplateElement(name, statisticsJson.getString("source"));
    }

    /**
     * Get the template element for the given polymer template source.
     *
     * @param fileName
     *         name of the handled file
     * @param source
     *         source js to get template element from
     * @return template element or {code null} if not found
     */
    public static Element parseTemplateElement(String fileName, String source) {

        ErrorReporter errorReporter = new SimpleErrorReporter();

        // parse a source file into an ast.
        SourceFile sourceFile = new SourceFile(fileName,
                StaticSourceFile.SourceKind.STRONG);

        ParserRunner.ParseResult parseResult = ParserRunner
                .parse(sourceFile, source, config, errorReporter);

        // run the visitor on the ast to extract the needed values.
        DependencyVisitor visitor = new DependencyVisitor();
        NodeUtil.visitPreOrder(parseResult.ast, visitor,
                Predicates.alwaysTrue());

        Document templateDocument = Jsoup
                .parse(visitor.getterContent.get(TEMPLATE_TAG_NAME));

        Element template = templateDocument.createElement(TEMPLATE_TAG_NAME);

        templateDocument.body().getAllElements().stream()
                .filter(node -> !node.equals(templateDocument.body()))
                .forEach(template::appendChild);

        return template;
    }

    /**
     * From the webpack statistics json go through all chunks to find the
     * requested module that has the name matching the file name.
     *
     * @param fileName
     *         id of module to find
     * @param statistics
     *         statistics json
     * @return JsonObject of file if found else {@code null}
     */
    private static JsonObject getObjectByFileName(String fileName,
            JsonObject statistics) {
        return getSourceObject(statistics, fileName);
    }

    // Visits all elements of a JsonArray and returns the first element with a valid source module
    private static JsonObject getSourceObjectFromArray(JsonArray objects, String name) {
        JsonObject object = null;
        for (int i = 0; object == null && i < objects.length(); i++) {
            if (objects.get(i).getType().equals(JsonType.OBJECT)) {
                object = getSourceObject(objects.get(i), name);
            }
        }
        return object;
    }

    // Recursively finds the first module whose name matches the file name
    private static JsonObject getSourceObject(JsonObject module, String name) {
        JsonObject object = null;
        if (module.hasKey("modules") && module.get("modules").getType().equals(JsonType.ARRAY)) {
            object = getSourceObjectFromArray(module.getArray("modules"), name);
        }
        if (object == null && module.hasKey("chunks") && module.get("chunks").getType().equals(JsonType.ARRAY)) {
            object = getSourceObjectFromArray(module.getArray("chunks"), name);
        }
        if (object == null && module.hasKey("name") && module.hasKey("source")) {
            if (module.getString("name").endsWith(name) && module.hasKey("source")
                    && module.get("source").getType().equals(JsonType.STRING)
                    && !module.getString("source").isEmpty()) {
                object = module;
            }
        }
        return object;
    }

    private static class DependencyVisitor implements NodeUtil.Visitor {

        private List<String> imports = new ArrayList<>();
        private List<String> getters = new ArrayList<>();

        Map<String, String> getterContent = new HashMap<>();

        @Override
        public void visit(Node node) {
            if (node != null) {
                switch (node.getToken()) {
                case IMPORT:
                    addImport(node);
                    break;
                case GETTER_DEF:
                    addGetter(node);
                    break;
                default:
                    break;
                }
            }
        }

        private void addGetter(Node node) {
            getters.add(node.getString());
            if (TEMPLATE_TAG_NAME.equals(node.getString())) {
                String content = getTextNode(node).getRawString();
                getterContent.put(node.getString(), content);
            }
        }

        private void addImport(Node node) {
            if (node.hasChildren()) {
                Node child = getTextNode(node);
                imports.add(child.getString());
            }
        }

        private Node getTextNode(Node node) {
            Node child = node.getFirstChild();
            while (child.getFirstChild() != null || child.getNext() != null) {
                if (child.getNext() == null) {
                    child = child.getFirstChild();
                } else {
                    child = child.getNext();
                }
            }
            return child;
        }
    }

}
