/*
 * Copyright (C) 2000-2024 Vaadin Ltd
 *
 * This program is available under Vaadin Commercial License and Service Terms.
 *
 * See <https://vaadin.com/commercial-license-and-service-terms> for the full
 * license.
 */
package com.vaadin.flow.webcomponent;

import org.junit.Assert;
import org.junit.Test;

import com.vaadin.flow.testutil.ChromeBrowserTest;
import com.vaadin.testbench.TestBenchElement;

public class StreamResourceIT extends ChromeBrowserTest {

    @Override
    protected String getTestPath() {
        return Constants.PAGE_CONTEXT + "/streamResource.html";
    }

    @Test
    public void absoluteUrlsAreNotModified() {
        open();

        TestBenchElement downloadLink = $("vaadin-stream-resource").first()
                .$("a").id("absoluteLink");

        String url = downloadLink.getAttribute("href");
        Assert.assertTrue(
                "Url is not generated by custom StreamResourceRegistry",
                url.contains("/vaadin-stream-resources-absolute/"));
        Assert.assertEquals(
                "Absolute url has been prefixed with other content: " + url, 0,
                url.lastIndexOf("http://"));
    }

    @Test
    public void schemaLessUrlsAreNotModified() {
        open();

        TestBenchElement downloadLink = $("vaadin-stream-resource").first()
                .$("a").id("schemalessLink");

        String url = downloadLink.getAttribute("href");
        Assert.assertTrue(
                "Url is not generated by custom StreamResourceRegistry",
                url.contains("/vaadin-stream-resources-absolute/"));
        Assert.assertEquals(
                "Absolute url has been prefixed with other content: " + url, 0,
                url.lastIndexOf("http://"));
    }

    @Test
    public void relativeUrlsArePrefixedWithServiceUrl() {
        open();

        TestBenchElement downloadLink = $("vaadin-stream-resource").first()
                .$("a").id("relativeLink");

        String url = downloadLink.getAttribute("href");
        Assert.assertTrue(
                "Url is not generated by custom StreamResourceRegistry",
                url.contains("/vaadin-stream-resources/"));
        Assert.assertEquals(
                "Absolute url has been prefixed with other content: " + url, 0,
                url.lastIndexOf("http://"));
    }

}
