/*
 * Copyright 2000-2026 Vaadin Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.vaadin.flow.server.streams;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.file.Files;

import org.slf4j.LoggerFactory;

import com.vaadin.flow.server.communication.TransferUtil;

/**
 * Abstract class for file upload handler.
 *
 * @param <R>
 *            type of file upload handler
 *
 * @since 24.8
 */
public abstract class AbstractFileUploadHandler<R extends AbstractFileUploadHandler>
        extends AbstractUploadHandler<R> {
    private final FileUploadCallback successCallback;
    private final FileFactory fileFactory;

    /**
     * Creates an upload callback that stores the incoming stream into a
     * {@link File} that is generated by the given {@link FileFactory}.
     *
     * @param successCallback
     *            consumer to be called for successful upload
     * @param fileFactory
     *            factory that generates the {@link File} to store data
     */
    public AbstractFileUploadHandler(FileUploadCallback successCallback,
            FileFactory fileFactory) {
        this.successCallback = successCallback;
        this.fileFactory = fileFactory;
    }

    @Override
    public void handleUploadRequest(UploadEvent event) throws IOException {
        UploadMetadata metadata = new UploadMetadata(event.getFileName(),
                event.getContentType(), event.getFileSize());
        setTransferUI(event.getUI());
        File file = null;
        try {
            runMetadataValidators(event);
            if (!event.isRejected()) {
                try (InputStream raw = event.getInputStream()) {
                    InputStream in = applyHeaderValidators(event, raw);
                    if (!event.isRejected()) {
                        // Create the file only once metadata and header passed,
                        // so a rejection leaves no file behind.
                        file = fileFactory.createFile(metadata);
                        try (FileOutputStream outputStream = new FileOutputStream(
                                file)) {
                            TransferUtil.transfer(in, outputStream,
                                    getTransferContext(event), getListeners());
                        }
                    }
                }
            }
        } catch (IOException e) {
            deleteAndNotify(event, file, e);
            throw e;
        } catch (RuntimeException e) {
            // A validator may throw an unchecked exception; still clean up.
            deleteQuietly(file);
            throw e;
        }
        if (hasValidators() && file != null && !event.isRejected()) {
            // Whole-content validation. Its streams are closed (try-with-
            // resources) before any deletion, so a validator leaving one open
            // can't block deletion. This runs after the transfer's onComplete
            // has already fired, so any failure here is reported via onError.
            try (FileUploadContent content = new FileUploadContent(file)) {
                runCompleteValidators(event, content);
            } catch (IOException e) {
                deleteAndNotify(event, file, e);
                throw e;
            } catch (RuntimeException e) {
                deleteQuietly(file);
                notifyError(event, new IOException(e));
                throw e;
            }
        }
        // A validator may reject the upload during any phase (metadata, header
        // or complete); all of them converge here. Rejection is fully settled
        // by this point, since every validator has already run. The transfer's
        // own onComplete may already have fired, so the rejection is surfaced
        // as a terminal onError to give progress listeners a definitive signal,
        // and the partially written file is discarded rather than delivered.
        if (event.isRejected()) {
            notifyError(event,
                    new UploadRejectedException(event.getRejectionMessage()));
            deleteQuietly(file);
            return;
        }
        final File uploadedFile = file;
        event.getUI().access(() -> {
            try {
                successCallback.complete(metadata, uploadedFile);
            } catch (IOException e) {
                throw new UncheckedIOException("Error in file upload callback",
                        e);
            }
        });
    }

    private void deleteAndNotify(UploadEvent event, File file, IOException e) {
        deleteQuietly(file);
        notifyError(event, e);
    }

    private static void deleteQuietly(File file) {
        if (file == null || !file.exists()) {
            return;
        }
        try {
            Files.delete(file.toPath());
        } catch (IOException e) {
            LoggerFactory.getLogger(AbstractFileUploadHandler.class)
                    .warn("Could not delete the file of a rejected or failed "
                            + "upload: {}", file.getAbsolutePath(), e);
        }
    }

    @Override
    protected TransferContext getTransferContext(UploadEvent transferEvent) {
        return new TransferContext(transferEvent.getRequest(),
                transferEvent.getResponse(), transferEvent.getSession(),
                transferEvent.getFileName(), transferEvent.getOwningElement(),
                transferEvent.getFileSize());
    }
}
