/*
 * Copyright (C) 2000-2026 Vaadin Ltd
 *
 * This program is available under Vaadin Commercial License and Service Terms.
 *
 * See <https://vaadin.com/commercial-license-and-service-terms> for the full
 * license.
 */
package com.vaadin.flow.server.streams;

import java.io.File;

import com.vaadin.flow.function.SerializableBiConsumer;

/**
 * Upload handler that stores the data into a file generated by the given
 * {@link FileFactory}.
 *
 * @since 24.8
 */
public class FileUploadHandler
        extends AbstractFileUploadHandler<FileUploadHandler> {

    /**
     * Constructor for file upload handler.
     *
     * @param successCallback
     *            consumer to be called when upload successfully completes
     * @param fileFactory
     *            factory for generating file to write to
     */
    public FileUploadHandler(FileUploadCallback successCallback,
            FileFactory fileFactory) {
        super(successCallback, fileFactory);
    }
}
