/*
 * Copyright 2000-2016 Vaadin Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.vaadin.server;

import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

/**
 * Registry for {@link StreamResource} instances.
 * 
 * @author Vaadin Ltd
 *
 */
public class StreamResourceRegistry implements Serializable {

    private static final char PATH_SEPARATOR = '/';

    /**
     * Dynamic resource URI prefix.
     */
    static final String DYN_RES_PREFIX = "VAADIN/dynamic/generated-resources/";

    private final Map<URI, StreamResource> resources = new HashMap<>();

    private final VaadinSession session;

    private int nextResourceId;

    private static final class Registration
            implements StreamResourceRegistration {

        private final StreamResourceRegistry registry;

        private final URI uri;

        private Registration(StreamResourceRegistry registry, int id,
                String fileName) {
            this.registry = registry;
            try {
                uri = new URI(generateURI(id, fileName));
            } catch (URISyntaxException e) {
                // this may not happen if implementation is correct
                throw new RuntimeException(e);
            }
        }

        @Override
        public URI getResourceUri() {
            return uri;
        }

        @Override
        public void unregister() {
            registry.resources.remove(getResourceUri());
        }

        private String generateURI(int id, String name) {
            StringBuilder builder = new StringBuilder(DYN_RES_PREFIX);
            try {
                builder.append(id).append(PATH_SEPARATOR).append(
                        URLEncoder.encode(name, StandardCharsets.UTF_8.name()));
            } catch (UnsupportedEncodingException e) {
                // UTF8 has to be supported
                throw new RuntimeException(e);
            }
            return builder.toString();
        }
    }

    /**
     * Creates stream resource registry for provided {@code session}.
     * 
     * @param session
     *            vaadin session
     */
    public StreamResourceRegistry(VaadinSession session) {
        this.session = session;
    }

    /**
     * Registers a stream resource in the session and returns registration
     * handler.
     * <p>
     * You can get resource URI to use it in the application (e.g. set an
     * attribute value or property value) via the registration handler. The
     * registration handler should be used to unregister resource when it's not
     * needed anymore. Note that it is the developer's responsibility to
     * unregister resources. Otherwise resources won't be garbage collected
     * until the session expires which causes memory leak.
     * 
     * @param resource
     *            stream resource to register
     * @return registration handler.
     */
    public StreamResourceRegistration registerResource(
            StreamResource resource) {
        assert session.hasLock();
        int id = nextResourceId;
        nextResourceId++;
        Registration registration = new Registration(this, id,
                resource.getFileName());
        resources.put(registration.getResourceUri(), resource);
        return registration;
    }

    /**
     * Get registered resource by its {@code path} (which has been generated by
     * the framework).
     * 
     * @param path
     *            resource path
     * @return registered resource if any
     */
    public Optional<StreamResource> getResource(String path) {
        assert session.hasLock();
        try {
            int index = path.lastIndexOf('/');
            boolean hasPrefix = index >= 0;
            if (!hasPrefix) {
                return Optional.empty();
            }
            String prefix = path.substring(0, index + 1);
            String name = path.substring(prefix.length());
            // path info returns decoded name but space ' ' remains encoded '+'
            name = name.replace('+', ' ');

            URI uri = new URI(prefix
                    + URLEncoder.encode(name, StandardCharsets.UTF_8.name()));
            return getResource(uri);
        } catch (UnsupportedEncodingException | URISyntaxException e) {
            // UTF8 has to be supported
            throw new RuntimeException(e);
        }
    }

    /**
     * Get registered resource by its {@code URI}.
     * 
     * @param uri
     *            resource URI
     * @return registered resource if any
     */
    private Optional<StreamResource> getResource(URI uri) {
        assert session.hasLock();
        return Optional.ofNullable(resources.get(uri));
    }

}
