/*
 * Copyright (C) 2000-2026 Vaadin Ltd
 *
 * This program is available under Vaadin Commercial License and Service Terms.
 *
 * See <https://vaadin.com/commercial-license-and-service-terms> for the full
 * license.
 */
package com.vaadin.flow.server.frontend;

import java.io.File;
import java.io.IOException;
import java.util.Collection;
import java.util.List;

/**
 * A base class for commands providing helpers for common file generation
 * actions.
 * <p>
 * </p>
 * By extending this class, commands can track generated files for subsequent
 * processes. In addition, it allows to avoid writes on disk of the file already
 * exists and has exactly the same generated content, preventing file system
 * watchers to trigger unnecessary events.
 *
 * @since 24.4
 */
public abstract class AbstractFileGeneratorFallibleCommand
        implements FallibleCommand {

    private GeneratedFilesSupport generatedFilesSupport = new GeneratedFilesSupport();

    @Override
    public void setGeneratedFileSupport(GeneratedFilesSupport support) {
        this.generatedFilesSupport = support;
    }

    /**
     * Writes the given content into the given file unless the file already
     * contains that content.
     *
     * @param file
     *            the file to write to
     * @param content
     *            the lines to write
     * @return true if the content was written to the file, false otherwise
     * @throws IOException
     *             if something went wrong
     */
    protected boolean writeIfChanged(File file, List<String> content)
            throws IOException {
        return generatedFilesSupport.writeIfChanged(file, content);
    }

    /**
     * Writes the given content into the given file unless the file already
     * contains that content.
     *
     * @param file
     *            the file to write to
     * @param content
     *            the content to write
     * @return true if the content was written to the file, false otherwise
     * @throws IOException
     *             if something went wrong
     */
    protected boolean writeIfChanged(File file, String content)
            throws IOException {
        return generatedFilesSupport.writeIfChanged(file, content);
    }

    /**
     * Marks the give file as generated by the task.
     *
     * @param file
     *            the file to be marked as generated.
     */
    protected void track(File file) {
        generatedFilesSupport.track(file);
    }

    /**
     * Marks the give files as generated by the task.
     *
     * @param files
     *            the collection of files to be marked as generated.
     */
    protected void track(Collection<File> files) {
        files.forEach(generatedFilesSupport::track);
    }

}
