
import io.gatling.core.Predef._
import io.gatling.http.Predef._

import scala.concurrent.duration._

class ExpenseCreation extends Simulation {

  val httpProtocol = http
    .baseURL("http://localhost:8888")
    .warmUp("http://localhost:8888/")
    .inferHtmlResources(BlackList(""".*\.js""", """.*\.css""", """.*\.gif""", """.*\.jpeg""", """.*\.jpg""", """.*\.ico""", """.*\.woff""", """.*\.(t|o)tf""", """.*\.png"""), WhiteList())
    .acceptHeader("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
    .acceptEncodingHeader("gzip, deflate")
    .acceptLanguageHeader("en-US,en;q=0.5")
    .userAgentHeader("Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0")

  val headers_1 = Map("Pragma" -> "no-cache")

  val headers_111 = Map(
    "Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Pragma" -> "no-cache")

  val url = "/"
  val uidlUrl = url + "?v-r=uidl&v-uiId=${uiId}"

  val uidlHeaders = Map("Content-Type" -> "application/json; charset=UTF-8")

  val storeUiId =
    regex(""""v-uiId":\s(\d+),""")
      .saveAs("uiId")
  val storeSecurityKey =
    regex(""""Vaadin-Security-Key":\s"([^"]*)""")
      .saveAs("securityKey")

  val incrementIds = exec((session) => {
    session.setAll(
      "syncId" -> (session.get("syncId").as[Int] + 1),
      "clientId" -> (session.get("clientId").as[Int] + 1)
    )
  })

  val initialRequest = exec(http("Open index page")
      .get(url)
      .check(bodyString.saveAs("RESPONSE_DATA"))
      .check(storeUiId)
      .check(storeSecurityKey)
    ).doIf(session => !session.contains("uiId")) {
      exec(session => {
        println("init failed with response:")
        println(session("RESPONSE_DATA").as[String])
        session
      }
      )
    }
    .exec(session => session.set("clientId", 0))
    .exec(session => session.set("syncId", 0))
    .pause(261 milliseconds)

  val getBowerFiles =
    exec(http("request_1")
      .get("/bower_components/expense-manager/src/elements.html")
      .headers(headers_1))
      .exec(http("request_2")
        .get("/bower_components/paper-fab/paper-fab.html")
        .headers(headers_1))
      .exec(http("request_3")
        .get("/bower_components/paper-icon-button/paper-icon-button.html")
        .headers(headers_1))
      .exec(http("request_4")
        .get("/bower_components/vaadin-grid/vaadin-grid.html")
        .headers(headers_1))
      .exec(http("request_5")
        .get("/bower_components/paper-button/paper-button.html")
        .headers(headers_1))
      .exec(http("request_6")
        .get("/bower_components/paper-checkbox/paper-checkbox.html")
        .headers(headers_1))
      .exec(http("request_7")
        .get("/bower_components/vaadin-combo-box/vaadin-combo-box.html")
        .headers(headers_1))
      .exec(http("request_8")
        .get("/bower_components/paper-input/paper-input.html")
        .headers(headers_1))
      .exec(http("request_9")
        .get("/bower_components/vaadin-date-picker/vaadin-date-picker.html")
        .headers(headers_1))
      .exec(http("request_10")
        .get("/bower_components/iron-icon/iron-icon.html")
        .headers(headers_1))
      .exec(http("request_11")
        .get("/bower_components/paper-toolbar/paper-toolbar.html")
        .headers(headers_1))
      .exec(http("request_12")
        .get("/bower_components/paper-header-panel/paper-header-panel.html")
        .headers(headers_1))
      .exec(http("request_13")
        .get("/bower_components/app-route/app-location.html")
        .headers(headers_1))
      .exec(http("request_14")
        .get("/bower_components/app-route/app-route.html")
        .headers(headers_1))
      .exec(http("request_15")
        .get("/bower_components/iron-a11y-keys/iron-a11y-keys.html")
        .headers(headers_1))
      .exec(http("request_16")
        .get("/bower_components/iron-ajax/iron-ajax.html")
        .headers(headers_1))
      .exec(http("request_17")
        .get("/bower_components/iron-form/iron-form.html")
        .headers(headers_1))
      .exec(http("request_18")
        .get("/bower_components/iron-icons/notification-icons.html")
        .headers(headers_1))
      .exec(http("request_19")
        .get("/bower_components/iron-localstorage/iron-localstorage.html")
        .headers(headers_1))
      .exec(http("request_20")
        .get("/bower_components/iron-media-query/iron-media-query.html")
        .headers(headers_1))
      .exec(http("request_21")
        .get("/bower_components/iron-pages/iron-pages.html")
        .headers(headers_1))
      .exec(http("request_22")
        .get("/bower_components/iron-icons/iron-icons.html")
        .headers(headers_1))
      .exec(http("request_23")
        .get("/bower_components/paper-dialog/paper-dialog.html")
        .headers(headers_1))
      .exec(http("request_24")
        .get("/bower_components/paper-input/paper-textarea.html")
        .headers(headers_1))
      .exec(http("request_25")
        .get("/bower_components/paper-toast/paper-toast.html")
        .headers(headers_1))
      .exec(http("request_26")
        .get("/bower_components/vaadin-charts/vaadin-bar-chart.html")
        .headers(headers_1))
      .exec(http("request_27")
        .get("/bower_components/polymer/polymer.html")
        .headers(headers_1))
      .exec(http("request_28")
        .get("/bower_components/vaadin-charts/vaadin-column-chart.html")
        .headers(headers_1))
      .exec(http("request_29")
        .get("/bower_components/vaadin-pouchdb/vaadin-pouchdb.html")
        .headers(headers_1))
      .exec(http("request_30")
        .get("/bower_components/vaadin-upload/vaadin-upload.html")
        .headers(headers_1))
      .exec(http("request_31")
        .get("/bower_components/iron-flex-layout/iron-flex-layout.html")
        .headers(headers_1))
      .exec(http("request_32")
        .get("/bower_components/paper-behaviors/paper-button-behavior.html")
        .headers(headers_1))
      .exec(http("request_33")
        .get("/bower_components/paper-material/paper-material-shared-styles.html")
        .headers(headers_1))
      .exec(http("request_34")
        .get("/bower_components/paper-styles/color.html")
        .headers(headers_1))
      .exec(http("request_35")
        .get("/bower_components/paper-styles/default-theme.html")
        .headers(headers_1))
      .exec(http("request_36")
        .get("/bower_components/paper-behaviors/paper-inky-focus-behavior.html")
        .headers(headers_1))
      .exec(http("request_37")
        .get("/bower_components/paper-behaviors/paper-checked-element-behavior.html")
        .headers(headers_1))
      .exec(http("request_38")
        .get("/bower_components/iron-input/iron-input.html")
        .headers(headers_1))
      .exec(http("request_39")
        .get("/bower_components/iron-validatable-behavior/iron-validatable-behavior.html")
        .headers(headers_1))
      .exec(http("request_40")
        .get("/bower_components/iron-a11y-announcer/iron-a11y-announcer.html")
        .headers(headers_1))
      .exec(http("request_41")
        .get("/bower_components/vaadin-combo-box/vaadin-combo-box-overlay.html")
        .headers(headers_1))
      .exec(http("request_42")
        .get("/bower_components/vaadin-combo-box/vaadin-combo-box-icons.html")
        .headers(headers_1))
      .exec(http("request_43")
        .get("/bower_components/paper-input/paper-input-container.html")
        .headers(headers_1))
      .exec(http("request_44")
        .get("/bower_components/iron-form-element-behavior/iron-form-element-behavior.html")
        .headers(headers_1))
      .exec(http("request_45")
        .get("/bower_components/paper-input/paper-input-behavior.html")
        .headers(headers_1))
      .exec(http("request_46")
        .get("/bower_components/paper-input/paper-input-error.html")
        .headers(headers_1))
      .exec(http("request_47")
        .get("/bower_components/paper-input/paper-input-char-counter.html")
        .headers(headers_1))
      .exec(http("request_48")
        .get("/bower_components/vaadin-combo-box/vaadin-combo-box-behavior.html")
        .headers(headers_1))
      .exec(http("request_49")
        .get("/bower_components/vaadin-combo-box/vaadin-combo-box-shared-styles.html")
        .headers(headers_1))
      .exec(http("request_50")
        .get("/bower_components/vaadin-date-picker/vaadin-date-picker-overlay.html")
        .headers(headers_1))
      .exec(http("request_51")
        .get("/bower_components/vaadin-date-picker/vaadin-date-picker-icons.html")
        .headers(headers_1))
      .exec(http("request_52")
        .get("/bower_components/paper-styles/typography.html")
        .headers(headers_1))
      .exec(http("request_53")
        .get("/bower_components/iron-location/iron-location.html")
        .headers(headers_1))
      .exec(http("request_54")
        .get("/bower_components/iron-dropdown/iron-dropdown.html")
        .headers(headers_1))
      .exec(http("request_55")
        .get("/bower_components/iron-meta/iron-meta.html")
        .headers(headers_1))
      .exec(http("request_56")
        .get("/bower_components/vaadin-date-picker/vaadin-date-picker-helper.html")
        .headers(headers_1))
      .exec(http("request_57")
        .get("/bower_components/vaadin-date-picker/vaadin-date-picker-behavior.html")
        .headers(headers_1))
      .exec(http("request_58")
        .get("/bower_components/iron-location/iron-query-params.html")
        .headers(headers_1))
      .exec(http("request_59")
        .get("/bower_components/app-route/app-route-converter-behavior.html")
        .headers(headers_1))
      .exec(http("request_60")
        .get("/bower_components/paper-ripple/paper-ripple.html")
        .headers(headers_1))
      .exec(http("request_61")
        .get("/bower_components/iron-a11y-keys-behavior/iron-a11y-keys-behavior.html")
        .headers(headers_1))
      .exec(http("request_62")
        .get("/bower_components/iron-iconset-svg/iron-iconset-svg.html")
        .headers(headers_1))
      .exec(http("request_63")
        .get("/bower_components/iron-ajax/iron-request.html")
        .headers(headers_1))
      .exec(http("request_64")
        .get("/bower_components/iron-resizable-behavior/iron-resizable-behavior.html")
        .headers(headers_1))
      .exec(http("request_65")
        .get("/bower_components/iron-selector/iron-selectable.html")
        .headers(headers_1))
      .exec(http("request_66")
        .get("/bower_components/neon-animation/neon-animation-runner-behavior.html")
        .headers(headers_1))
      .exec(http("request_67")
        .get("/bower_components/paper-dialog-behavior/paper-dialog-behavior.html")
        .headers(headers_1))
      .exec(http("request_68")
        .get("/bower_components/paper-dialog-behavior/paper-dialog-shared-styles.html")
        .headers(headers_1))
      .exec(http("request_69")
        .get("/bower_components/iron-autogrow-textarea/iron-autogrow-textarea.html")
        .headers(headers_1))
      .exec(http("request_70")
        .get("/bower_components/iron-overlay-behavior/iron-overlay-behavior.html")
        .headers(headers_1))
      .exec(http("request_71")
        .get("/bower_components/vaadin-license-checker/vaadin-license-checker.html")
        .headers(headers_1))
      .exec(http("request_72")
        .get("/bower_components/vaadin-charts/data-series.html")
        .headers(headers_1))
      .exec(http("request_73")
        .get("/bower_components/vaadin-charts/valo-theme.html")
        .headers(headers_1))
      .exec(http("request_74")
        .get("/bower_components/vaadin-charts/chart-behavior.html")
        .headers(headers_1))
      .exec(http("request_75")
        .get("/bower_components/vaadin-upload/vaadin-upload-icons.html")
        .headers(headers_1))
      .exec(http("request_76")
        .get("/bower_components/vaadin-upload/vaadin-upload-file.html")
        .headers(headers_1))
      .exec(http("request_77")
        .get("/bower_components/polymer/polymer-mini.html")
        .headers(headers_1))
      .exec(http("request_78")
        .get("/bower_components/iron-behaviors/iron-button-state.html")
        .headers(headers_1))
      .exec(http("request_79")
        .get("/bower_components/paper-behaviors/paper-ripple-behavior.html")
        .headers(headers_1))
      .exec(http("request_80")
        .get("/bower_components/paper-styles/shadow.html")
        .headers(headers_1))
      .exec(http("request_81")
        .get("/bower_components/iron-checked-element-behavior/iron-checked-element-behavior.html")
        .headers(headers_1))
      .exec(http("request_82")
        .get("/bower_components/iron-list/iron-list.html")
        .headers(headers_1))
      .exec(http("request_83")
        .get("/bower_components/vaadin-combo-box/vaadin-overlay-behavior.html")
        .headers(headers_1))
      .exec(http("request_84")
        .get("/bower_components/vaadin-combo-box/vaadin-spinner.html")
        .headers(headers_1))
      .exec(http("request_85")
        .get("/bower_components/iron-behaviors/iron-control-state.html")
        .headers(headers_1))
      .exec(http("request_86")
        .get("/bower_components/paper-input/paper-input-addon-behavior.html")
        .headers(headers_1))
      .exec(http("request_87")
        .get("/bower_components/vaadin-combo-box/vaadin-dropdown-behavior.html")
        .headers(headers_1))
      .exec(http("request_88")
        .get("/bower_components/vaadin-date-picker/vaadin-infinite-scroller.html")
        .headers(headers_1))
      .exec(http("request_89")
        .get("/bower_components/vaadin-date-picker/vaadin-month-calendar.html")
        .headers(headers_1))
      .exec(http("request_90")
        .get("/bower_components/font-roboto/roboto.html")
        .headers(headers_1))
      .exec(http("request_91")
        .get("/bower_components/neon-animation/animations/opaque-animation.html")
        .headers(headers_1))
      .exec(http("request_92")
        .get("/bower_components/iron-dropdown/iron-dropdown-scroll-manager.html")
        .headers(headers_1))
      .exec(http("request_93")
        .get("/bower_components/promise-polyfill/promise-polyfill-lite.html")
        .headers(headers_1))
      .exec(http("request_94")
        .get("/bower_components/iron-selector/iron-selection.html")
        .headers(headers_1))
      .exec(http("request_95")
        .get("/bower_components/neon-animation/neon-animatable-behavior.html")
        .headers(headers_1))
      .exec(http("request_96")
        .get("/bower_components/iron-fit-behavior/iron-fit-behavior.html")
        .headers(headers_1))
      .exec(http("request_97")
        .get("/bower_components/iron-overlay-behavior/iron-overlay-manager.html")
        .headers(headers_1))
      .exec(http("request_98")
        .get("/bower_components/iron-overlay-behavior/iron-focusables-helper.html")
        .headers(headers_1))
      .exec(http("request_99")
        .get("/bower_components/vaadin-license-checker/vaadin-license-box.html")
        .headers(headers_1))
      .exec(http("request_100")
        .get("/bower_components/vaadin-license-checker/vaadin-license-dialog.html")
        .headers(headers_1))
      .exec(http("request_101")
        .get("/bower_components/vaadin-license-checker/vaadin-license-notification.html")
        .headers(headers_1))
      .exec(http("request_102")
        .get("/bower_components/vaadin-license-checker/vaadin-framework-identifier.html")
        .headers(headers_1))
      .exec(http("request_103")
        .get("/bower_components/vaadin-charts/configuration-reader.html")
        .headers(headers_1))
      .exec(http("request_104")
        .get("/bower_components/paper-progress/paper-progress.html")
        .headers(headers_1))
      .exec(http("request_105")
        .get("/bower_components/polymer/polymer-micro.html")
        .headers(headers_1))
      .exec(http("request_106")
        .get("/bower_components/iron-scroll-target-behavior/iron-scroll-target-behavior.html")
        .headers(headers_1))
      .exec(http("request_107")
        .get("/bower_components/neon-animation/neon-animation-behavior.html")
        .headers(headers_1))
      .exec(http("request_108")
        .get("/bower_components/neon-animation/web-animations.html")
        .headers(headers_1))
      .exec(http("request_109")
        .get("/bower_components/iron-overlay-behavior/iron-overlay-backdrop.html")
        .headers(headers_1))
      .exec(http("request_110")
        .get("/bower_components/iron-range-behavior/iron-range-behavior.html")
        .headers(headers_1))
      .pause(2)
      .exec(http("request_111")
        .get("/bower_components/web-animations-js/web-animations-next-lite.min.js.map")
        .headers(headers_111))
      .pause(1)

  val loadPage =
    exec(http("Request Items 0-50")
      .post(uidlUrl)
      .headers(uidlHeaders)
      .body(ElFileBody("RecordedSimulation_0112_request.txt"))
    )
      .exec(incrementIds)

      .pause(854 milliseconds)
      .exec(http("Request Items 51-75")
        .post(uidlUrl)
        .headers(uidlHeaders)
        .body(ElFileBody("RecordedSimulation_0113_request.txt"))
      )
      .exec(incrementIds)

      .pause(4)
  // load

  val openNewExpense =
    exec(http("pSync properties")
      .post(uidlUrl)
      .headers(uidlHeaders)
      .body(ElFileBody("RecordedSimulation_0114_request.txt"))
    )
      .exec(incrementIds)
      .exec(http("Click new expense")
        .post(uidlUrl)
        .headers(uidlHeaders)
        .body(ElFileBody("RecordedSimulation_0115_request.txt"))
        .check(regex("""add":\["cancel"""))
      )
      .exec(incrementIds)
      .pause(7)


  // Open new Expense

  val cancelNewExpense =
    exec(http("pSync properties")
      .post(uidlUrl)
      .headers(uidlHeaders)
      .body(ElFileBody("RecordedSimulation_0116_request.txt"))
    )
      .exec(incrementIds)

//      .exec(http("request_117")
//        .post(uidlUrl)
//        .headers(uidlHeaders)
//        .body(ElFileBody("RecordedSimulation_0117_request.txt"))
//      )
//      .exitHereIfFailed
//      .exec(incrementIds)

      .pause(419 milliseconds)
      .exec(http("Click cancel in expense window")
        .post(uidlUrl)
        .headers(uidlHeaders)
        .body(ElFileBody("RecordedSimulation_0118_request.txt"))
      )
      .exec(incrementIds)

      .pause(933 milliseconds)
      .exec(http("Request Items 51-75")
        .post(uidlUrl)
        .headers(uidlHeaders)
        .body(ElFileBody("RecordedSimulation_0119_request.txt")))
      .exec(incrementIds)
  // cancel

// Add .exitHereIfFailed.exec(getBowerFiles) after initialRequest if we want to test with those too.
  val scn = scenario("RecordedSimulation").exec(
    initialRequest).exitHereIfFailed.exec(loadPage).exitHereIfFailed.exec(openNewExpense).exitHereIfFailed.exec(cancelNewExpense)

  setUp(scn.inject(rampUsers(1000) over (120 seconds))).protocols(httpProtocol)

  /* To get response data for exec post add to Exec after body add:

  .check( bodyString.saveAs( "RESPONSE_DATA" ) )
    )
      .exec( session => {
        println( "0016:" )
        println( session( "RESPONSE_DATA" ).as[String] )
        session
      }
    */
}