name: Check User Permissions

on:
  workflow_call:
    outputs:
      has-permission:
        description: 'Whether the user has write permission'
        value: ${{ jobs.check.outputs.has-permission }}

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      has-permission: ${{ steps.checkUser.outputs.require-result }}
    steps:
      - uses: actions-cool/check-user-permission@main
        id: checkUser
        with:
          username: ${{ github.triggering_actor }}
          require: 'write'

      - name: Fail on external workflow triggering
        if: ${{ steps.checkUser.outputs.require-result != 'true' && github.actor != 'dependabot[bot]' }}
        run: |
          echo "🚫 **${{ github.actor }}** is an external contributor, a **${{ github.repository }}** team member has to review this changes and re-run this build" \
            | tee -a $GITHUB_STEP_SUMMARY && exit 1
