name: Claude Code Review

on:
  issue_comment:
    types: [created]

jobs:
  claude-review:
    if: |
      github.event.issue.pull_request &&
      contains(toLower(github.event.comment.body), 'claude review')

    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Read review-pr command
        id: read-command
        run: |
          # Read the command file and export as output
          COMMAND_CONTENT=$(cat .claude/commands/review-pr.md)
          # Use heredoc to preserve multiline content
          {
            echo 'command<<EOF'
            echo "$COMMAND_CONTENT"
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            ${{ steps.read-command.outputs.command }}

            PR_NUMBER: ${{ github.event.issue.number }}
