name: Flow Validation
on:
  push:
    branches: ['25.3', '25.2', '25.1', '25.0', '24.10', '24.9', '24.7', '24.4', '23.7', '23.6']
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    outputs:
      matrix-unit: ${{ steps.set-matrix.outputs.matrix-unit }}
      matrix-it: ${{ steps.set-matrix.outputs.matrix-it }}
    steps:
      - run: echo "Concurrency Group = ${{ github.head_ref || github.ref_name }}"
      - name: Check secrets
        if: ${{ !github.event.pull_request.head.repo.fork }}
        env:
          TB_LICENSE: ${{ secrets.TB_LICENSE }}
        run: |
          [ -z "$TB_LICENSE" ] \
            && echo "🚫 **TB_LICENSE** is not defined, check that **${{github.repository}}** repo has a valid secret" \
            | tee -a $GITHUB_STEP_SUMMARY && exit 1 || exit 0
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '22.23.2'
      - name: Set up JDK 17
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set flow version to 999.99-SNAPSHOT
        run: |
          ./scripts/computeMatrix.js set-version --version=999.99-SNAPSHOT
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Generate matrices
        id: set-matrix
        run: |
          echo "matrix-it=$(./scripts/computeMatrix.js it-tests --parallel=13 current module args)" >> $GITHUB_OUTPUT
          echo "matrix-unit=$(./scripts/computeMatrix.js unit-tests --parallel=2 current module args)" >> $GITHUB_OUTPUT
      - name: Compile and Install Flow
        run: |
          cmd="mvn install -B -ntp -DskipTests  -pl \!flow-plugins/flow-gradle-plugin"
          eval $cmd -T 2C -q || eval $cmd
      - name: Save workspace
        run: |
          tar cf workspace.tar -C ~/ $(cd ~/ && echo .m2/repository/com/vaadin/*/999.99-SNAPSHOT)
          tar rf workspace.tar $(find . -d -name target)
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: saved-workspace
          path: workspace.tar
  unit-tests:
    needs: build
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.build.outputs.matrix-unit)}}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up JDK 17
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set flow version to 999.99-SNAPSHOT
        run: |
          ./scripts/computeMatrix.js set-version --version=999.99-SNAPSHOT
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        if: ${{ github.run_attempt == 1 }}
        with:
          name: saved-workspace
      - name: Restore Workspace
        if: ${{ github.run_attempt == 1 }}
        run: |
          set -x
          tar xf workspace.tar
          tar cf - .m2 | (cd ~ && tar xf -)
      - name: Compile and Install Flow
        if: ${{ github.run_attempt > 1 }}
        run: |
          ./scripts/computeMatrix.js set-version --version=999.99-SNAPSHOT
          cmd="mvn install -B -ntp -DskipTests  -pl \!flow-plugins/flow-gradle-plugin"
          eval $cmd -T 2C -q || eval $cmd
      - name: Set TB License
        run: |
          TB_LICENSE=${{secrets.TB_LICENSE}}
          mkdir -p ~/.vaadin/
          echo '{"username":"'`echo $TB_LICENSE | cut -d / -f1`'","proKey":"'`echo $TB_LICENSE | cut -d / -f2`'"}' > ~/.vaadin/proKey
      - name: Unit Test
        run: |
          echo Running TESTS: ${{ strategy.job-index }} ${{matrix.module}} ${{ matrix.args }}
          [ -n "${{matrix.module}}" ] && \
            ARGS="-pl ${{matrix.module}} -Dtest=${{matrix.args}}" || \
            ARGS="-pl ${{matrix.args}}"
          cmd="mvn -B -ntp -T 1C $ARGS"
          set -x -e -o pipefail
          $cmd verify -Dmaven.javadoc.skip=false | tee mvn-unit-tests-${{matrix.current}}.out
      - name: Package test-report files
        if: ${{ failure() || success() }}
        run: find . -name surefire-reports -o -name failsafe-reports -o -name error-screenshots -o -name "mvn-*.out" | tar -czf tests-report-unit-${{matrix.current}}.tgz -T -
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ failure() || success() }}
        with:
          name: tests-output-unit-${{ matrix.current }}
          path: tests-report-*.tgz
  it-tests:
    needs: build
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.build.outputs.matrix-it)}}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '22.23.2'
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: '8.15.9'
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: 'latest'
      - name: Set up JDK 17
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set flow version to 999.99-SNAPSHOT
        run: |
          ./scripts/computeMatrix.js set-version --version=999.99-SNAPSHOT
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        if: ${{ github.run_attempt == 1 }}
        with:
          name: saved-workspace
      - name: Restore Workspace
        if: ${{ github.run_attempt == 1 }}
        run: |
          tar xf workspace.tar
          tar cf - .m2 | (cd ~ && tar xf -)
      - name: Compile and Install Flow
        if: ${{ github.run_attempt > 1 }}
        run: |
          ./scripts/computeMatrix.js set-version --version=999.99-SNAPSHOT
          cmd="mvn install -B -ntp -DskipTests  -pl \!flow-plugins/flow-gradle-plugin"
          eval $cmd -T 2C -q || eval $cmd
      - name: Set TB License
        run: |
          TB_LICENSE=${{secrets.TB_LICENSE}}
          mkdir -p ~/.vaadin/
          echo '{"username":"'`echo $TB_LICENSE | cut -d / -f1`'","proKey":"'`echo $TB_LICENSE | cut -d / -f2`'"}' > ~/.vaadin/proKey
      - name: Compile Shared modules
        run: |
          if [ ${{matrix.current}} -eq 2 -o ${{matrix.current}} -eq 3 ]; then
            cmd="mvn install -B -ntp -DskipTests -Pit-shared-modules -amd -pl flow-tests"
            $cmd -T 1C || $cmd
          fi
          if [ ${{matrix.current}} -eq 4 -o ${{matrix.current}} -eq 5 -o ${{matrix.current}} -eq 6 ]; then
            cmd="mvn install -B -ntp -DskipTests -Pit-shared-spring-modules -amd -pl flow-tests"
            $cmd -T 1C || $cmd
          fi
      - name: Run ITs
        run: |
          [ -n "${{matrix.module}}" ] && \
            ARGS="-Dfailsafe.forkCount=4 -pl ${{matrix.module}} -Dit.test=${{matrix.args}}" || \
            ARGS="-pl ${{matrix.args}}"
          cmd="mvn -V -B -ntp -e -fae -Dcom.vaadin.testbench.Parameters.testsInParallel=5 -Dfailsafe.rerunFailingTestsCount=2 -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Pbun $ARGS"
          set -x -e -o pipefail
          $cmd verify | tee -a mvn-it-tests-${{matrix.current}}.out
      - name: Package test-report files
        if: ${{ failure() || success() }}
        run: find . -name surefire-reports -o -name failsafe-reports -o -name error-screenshots -o -name "mvn-*.out" | tar -czf tests-report-it-${{matrix.current}}.tgz -T -
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ failure() || success() }}
        with:
          name: tests-output-it-${{ matrix.current }}
          path: tests-report-*.tgz
  test-results:
    permissions:
      actions: write
      issues: read
      checks: write
      pull-requests: write
    if: ${{ failure() || success() }}
    needs: [unit-tests, it-tests]
    runs-on: ubuntu-24.04
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: tests-output
          pattern: tests-output-*
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: tests-output
      - name: extract downloaded files
        run: for i in *.tgz; do tar xvf $i; done
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        with:
          junit_files: "**/target/*-reports/TEST*.xml"
          check_run_annotations: all tests, skipped tests
      - uses: geekyeggo/delete-artifact@176a747ab7e287e3ff4787bf8a148716375ca118 # v6.0.0
        with:
          name: |
            saved-workspace
      - name: Compute Stats
        run: |
          ./scripts/computeMatrix.js test-results >> $GITHUB_STEP_SUMMARY
      - name: Set Failure Status
        if: ${{ always() && (needs.unit-tests.result != 'success' || needs.it-tests.result != 'success') }}
        run: |
            echo "🚫 THERE ARE TEST MODULES WITH FAILURES or BEEN CANCELLED" | tee -a $GITHUB_STEP_SUMMARY
            exit 1
